Repository yaklang/yakit, pull requests merged in 2023-09, with the labels that each got.

#1026 Song/feat/up or down select row
  app/renderer/src/main/package.json
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
  app/renderer/src/main/src/pages/assetViewer/PortAssetPage.tsx
  app/renderer/src/main/src/pages/cve/CVETable.tsx
  app/renderer/src/main/src/pages/fuzzer/components/HTTPFuzzerPageTable/HTTPFuzzerPageTable.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMLog.tsx
  app/renderer/src/main/yarn.lock
Labels: ready

#1018 Rookie/feature/new codec
  app/main/handlers/codec.js
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/new-codec/NewCodecPage.tsx
  app/renderer/src/main/src/pages/new-codec/style.module.css
  app/renderer/src/main/src/routes/newRoute.tsx
Labels: ready, WIP: work in progress

#1022 fix(webfuzzer-redirect):webfuzzer重定向修复
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
Labels: ready

#1031 report
  app/renderer/src/main/src/pages/simpleDetect/CreatReportScript.js
Labels: 发版后合

#1035 优化表格出现在页面可视区写法 采用useInViewport
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
Labels: ready

#1043 Luoluo/style/fuzzer sequence
  app/renderer/src/main/src/components/yakitUI/YakitInput/YakitInput.module.scss
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.module.scss
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/WebFuzzerPage/WebFuzzerPage.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/renderSubPage/RenderSubPage.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
Labels: ready

#1048 Song/fix/editor input val vanish
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerHotPatch.tsx
  app/renderer/src/main/src/pages/payloadManager/PayloadManager.tsx
Labels: ready

#1046 feat: 设置菜单菜单项顺序调整
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
Labels: ready

#1044 Feature/go0p/fuzzer params type raw
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.module.scss
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfigType.d.ts
Labels: ready

#1052 Song/feat/history page editor add copy url
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/yakitUI/YakitMenu/showByRightContext.tsx
Labels: ready

#1056 perf: Web Fuzzer页面响应部分搜索icon切换输入框范围修改
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
Labels: ready

#1058 Song/fix/risk page list order
  app/renderer/src/main/src/pages/risks/RiskTable.tsx
Labels: ready

#1061 fix: history页面表格响应大小筛选匹配问题
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
Labels: ready

#1062 Song/feat/mitm page clean btn adjust
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMLog.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.module.scss
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.tsx
Labels: ready

#1064 Song/fix/port asset table scroll
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
Labels: ready

#1071 feat: 录屏新增倍速
  app/renderer/src/main/src/pages/screenRecorder/ScrecorderModal.tsx
  app/renderer/src/main/src/pages/screenRecorder/ScreenRecorder.module.scss
  app/renderer/src/main/src/pages/screenRecorder/ScreenRecorderList.tsx
Labels: ready

#1073 feat: 阻止编辑器点击URL默认打开行为 自定义外部系统默认浏览器打开URL
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
Labels: ready

#1074 Song/pref/history editor data source
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/HTTPHistory.tsx
Labels: ready

#1075 feat: MITM若替换规则开启弹窗提示
  app/renderer/src/main/src/pages/mitm/MITMChromeLauncher.tsx
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMServerStartForm.tsx
Labels: ready

#1067 Luoluo/feature/sequence cache
  app/main/handlers/communication.js
  app/renderer/src/main/package.json
  app/renderer/src/main/src/components/baseConsole/StoreConsole.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerHistory.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.tsx
  app/renderer/src/main/src/pages/fuzzer/WebFuzzerPage/WebFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/WebFuzzerPage/WebFuzzerPageType.d.ts
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContentType.d.ts
  app/renderer/src/main/src/pages/layout/mainOperatorContent/renderSubPage/RenderSubPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMRule/MITMRule.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/store/comment.ts
  app/renderer/src/main/src/store/fuzzerSequence.ts
  app/renderer/src/main/src/store/index.ts
  app/renderer/src/main/src/store/pageInfo.ts
  app/renderer/src/main/src/store/pageNodeInfo.ts
  app/renderer/src/main/src/store/screenRecorder.ts
  app/renderer/src/main/src/store/tabSubscribe.ts
  app/renderer/src/main/src/utils/editors.tsx
  app/renderer/src/main/src/utils/eventBus/events/webFuzzer.ts
  app/renderer/src/main/src/yakitGV.ts
  app/renderer/src/main/yarn.lock
Labels: ready

#1079 feat: Web Fuzzer Table Col Adjust
  app/renderer/src/main/src/pages/fuzzer/components/HTTPFuzzerPageTable/HTTPFuzzerPageTable.tsx
Labels: ready

#1078 pref: 文本样式导出新增loading
  app/renderer/src/main/src/components/DataExport/DataExport.tsx
  app/renderer/src/main/src/pages/yakitStore/viewers/WebsiteTree.module.scss
  app/renderer/src/main/src/pages/yakitStore/viewers/WebsiteTree.tsx
Labels: ready

#1077 Luoluo/feature/history remove
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerHistory.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
Labels: ready

#1085 add clearInterval
  app/renderer/src/main/src/pages/chaosmaker/ChaosMakerOperators.tsx
Labels: ready

#1086 Yj/feature/history/old res rsp
  app/main/handlers/queryHTTPFlow.js
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/HTTPHistory.tsx
  app/renderer/src/main/src/components/ResizeCardBox/ResizeCardBox.module.scss
  app/renderer/src/main/src/components/ResizeCardBox/ResizeCardBox.tsx
  app/renderer/src/main/src/components/hTTPFlowDetail.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditorType.ts
  app/renderer/src/main/src/components/yakitUI/YakitEditor/contextMenus.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
  app/renderer/src/main/src/pages/compare/DataCompare.module.scss
  app/renderer/src/main/src/pages/compare/DataCompare.tsx
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.module.scss
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.module.scss
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/WebFuzzerNewEditor/WebFuzzerNewEditor.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMFiltersModal.tsx
  app/renderer/src/main/src/utils/editors.tsx
  app/renderer/src/main/src/utils/encodec.tsx
  app/renderer/src/main/src/utils/prettifyPacket.tsx
Labels: ready

#1081 Song/pref/web fuzzer select color
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/WebFuzzerPage/WebFuzzerPage.module.scss
  app/renderer/src/main/src/pages/fuzzer/WebFuzzerPage/WebFuzzerPage.tsx
  app/renderer/src/main/src/utils/eventBus/events/webFuzzer.ts
Labels: ready

#1092 fix: 弹窗出现条件修复
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMServerStartForm.tsx
Labels: ready

#1096 Yj/refactor/simple/09 18
  app/renderer/src/main/src/pages/assetViewer/ReportViewer.tsx
  app/renderer/src/main/src/pages/assetViewer/reportRenders/EchartsInit.module.scss
  app/renderer/src/main/src/pages/assetViewer/reportRenders/EchartsInit.tsx
  app/renderer/src/main/src/pages/assetViewer/reportRenders/render.tsx
  app/renderer/src/main/src/pages/simpleDetect/CreatReportScript.js
  app/renderer/src/main/src/pages/simpleDetect/SimpleDetect.tsx
  app/renderer/src/main/src/pages/yakitStore/store/PluginStore.tsx
  report/template.zip
Labels: ready

#1100 Song/feat/default ip set
  app/renderer/src/main/src/pages/mitm/MITMChromeLauncher.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMServerStartForm.tsx
Labels: ready

#1097 fix(mitm): cancel hijack response
  app/main/handlers/mitm.js
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMHijackedContent.tsx
Labels: ready

#1102 Song/pref/history editor data source
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMLog.tsx
Labels: ready

#1104 Yj/feature/multi history
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/HTTPHistory.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
  app/renderer/src/main/src/components/baseConsole/BaseConsole.tsx
  app/renderer/src/main/src/components/hTTPFlowDetail.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditorType.ts
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
  app/renderer/src/main/src/pages/compare/DataCompare.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMHijackedContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMLog.tsx
  app/renderer/src/main/src/store/baseConsole.tsx
  app/renderer/src/main/src/store/mitmState.ts
  app/renderer/src/main/src/utils/editors.module.scss
  app/renderer/src/main/src/utils/editors.tsx
  app/renderer/src/main/src/utils/eventBus/eventBus.ts
  app/renderer/src/main/src/utils/eventBus/events/editor.ts
Labels: ready

#1107 fix: 劫持部分加载处理
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMLog.tsx
Labels: ready

#1112 fix: hotPatchCode存store 解决ref拿不到最新值问题
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/store/fuzzerSequence.ts
Labels: ready

#1116 feat: 调整yakit-menu样式，接入theme
  app/renderer/src/main/src/components/yakitUI/YakitEditor/EditorMenu.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/components/yakitUI/YakitMenu/YakitMenu.tsx
  app/renderer/src/main/src/components/yakitUI/YakitMenu/index.md
  app/renderer/src/main/src/components/yakitUI/YakitMenu/yakitMenu.module.scss
  app/renderer/src/main/src/pages/layout/HeardMenu/HeardMenu.tsx
  app/renderer/src/main/src/pages/mitm/MITMRule/MITMRule.tsx
  app/renderer/src/main/src/pages/screenRecorder/ScreenRecorderList.tsx
  app/renderer/src/main/src/theme/yakit.scss
Labels: ready

#1114 Yj/feature/chrome user
  app/main/handlers/chromelauncher.js
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/pages/mitm/MITMChromeLauncher.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMFormAdvancedConfiguration.tsx
Labels: ready

#1113 fix(dnslog) clear token
  app/renderer/src/main/src/pages/dnslog/DNSLogPage.tsx
  app/renderer/src/main/src/pages/layout/publicMenu/MenuDNSLog.tsx
Labels: ready
