Repository yaklang/yakit, pull requests merged in 2023-11, with the labels that each got.

#1171 Yj/feature/history table
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/HTTPHistory.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResizeType.d.ts
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/yakitUI/YakitResizeBox/YakitResizeBox.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfigType.d.ts
  app/renderer/src/main/src/pages/invoker/ExecYakScript.tsx
  app/renderer/src/main/src/pages/invoker/YakScriptCreator.tsx
  app/renderer/src/main/src/pages/mitm/MITMChromeLauncher.tsx
  app/renderer/src/main/src/pages/mitm/MITMConsts.tsx
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMHijackedContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMLog.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMServerStartForm.tsx
  app/renderer/src/main/src/pages/websocket/WebsocketFlowHistory.tsx
  app/renderer/src/main/src/pages/yakitStore/viewers/base.tsx
  app/renderer/src/main/src/utils/eventBus/events/mitm.ts
  app/renderer/src/main/src/utils/eventBus/events/webFuzzer.ts
Labels: ready

#1177 Song/feat/chart cs support drag
  app/renderer/src/main/src/pages/MainOperator.tsx
  app/renderer/src/main/src/pages/main.scss
Labels: ready

#1178 Song/style/plugin debugger page
  app/renderer/src/main/src/pages/httpRequestBuilder/HTTPRequestBuilder.tsx
  app/renderer/src/main/src/pages/pluginDebugger/PluginDebuggerPage.module.scss
  app/renderer/src/main/src/pages/pluginDebugger/PluginDebuggerPage.tsx
  app/renderer/src/main/src/pages/yakitStore/viewers/base.scss
  app/renderer/src/main/src/pages/yakitStore/viewers/base.tsx
Labels: ready

#1181 Yj/feature/chat cs
  app/main/handlers/mitm.js
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/HTTPHistory.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResizeType.d.ts
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/yakChat/ChatMarkdown.tsx
  app/renderer/src/main/src/components/yakChat/chatCS.module.scss
  app/renderer/src/main/src/components/yakChat/chatCS.tsx
  app/renderer/src/main/src/components/yakChat/chatCSType.ts
  app/renderer/src/main/src/components/yakChat/icon.tsx
  app/renderer/src/main/src/components/yakitUI/YakitTabs/YakitTabs.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/components/HTTPFuzzerPageTable/HTTPFuzzerPageTable.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMFilters.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMFiltersModal.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMFormAdvancedConfiguration.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMServerStartForm.module.scss
  app/renderer/src/main/src/pages/pluginDebugger/PluginDebuggerPage.tsx
  app/renderer/src/main/src/pages/yakitStore/viewers/base.tsx
  app/renderer/src/main/src/services/yakChat.ts
  app/renderer/src/main/src/utils/eventBus/eventBus.ts
  app/renderer/src/main/src/utils/eventBus/events/history.ts
  app/renderer/src/main/src/utils/eventBus/events/webFuzzer.ts
Labels: ready

#1176 use hex editor
  app/renderer/src/main/src/components/playground/ChaosMakerRulesDemo.tsx
  app/renderer/src/main/src/pages/debugMonaco/DebugMonacoEditorPage.tsx
Labels: Experimental Features

#1186 improve yakurl
  app/renderer/src/main/src/pages/debugMonaco/DebugMonacoEditorPage.tsx
  app/renderer/src/main/src/pages/yakURLTree/YakURLTree.tsx
Labels: Experimental Features

#1187 Yj/fix/simple detect/11 09
  app/renderer/src/main/src/pages/portscan/PortScanPage.tsx
  app/renderer/src/main/src/pages/portscan/schema.ts
Labels: ready

#1190 fix: 只有拖拽对象为chartCSDragItem是才进行拖动
  app/renderer/src/main/src/pages/MainOperator.tsx
Labels: ready

#1191 fix: 切换源码与执行结果通过css来判断元素是否显示
  app/renderer/src/main/src/pages/pluginDebugger/PluginDebuggerPage.tsx
Labels: ready

#1192 Song/feat/run node
  app/main/handlers/engineStatus.js
  app/renderer/src/main/src/components/css/globalState.module.css
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/layout/GlobalState.tsx
  app/renderer/src/main/src/components/layout/MacUIOp.tsx
  app/renderer/src/main/src/components/layout/WinUIOp.tsx
  app/renderer/src/main/src/components/layout/globalState.module.scss
  app/renderer/src/main/src/store/runNode.tsx
Labels: ready

#1197 Yj/fix/many fuzzer
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/HTTPHistory.tsx
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPageExport.tsx
  app/renderer/src/main/src/pages/fuzzer/components/HTTPFuzzerPageTable/HTTPFuzzerPageTable.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMLog.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/utils/eventBus/events/history.ts
Labels: WIP: work in progress

#1202 Song/feat/history tree
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/HTTPHistory.module.scss
  app/renderer/src/main/src/components/HTTPHistory.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResizeType.d.ts
  app/renderer/src/main/src/components/hTTPFlowDetail.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitResizeBox/YakitResizeBox.tsx
  app/renderer/src/main/src/components/yakitUI/YakitTree/YakitTree.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitTree/YakitTree.tsx
  app/renderer/src/main/src/pages/assetViewer/PortAssetPage.tsx
  app/renderer/src/main/src/pages/yakURLTree/YakURLTree.tsx
  app/renderer/src/main/src/pages/yakitStore/viewers/base.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/utils/eventBus/events/history.ts
  app/renderer/src/main/src/yakitGV.ts
Labels: ready

#1218 Song/feat/agent config
  app/main/handlers/mitm.js
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMServerStartForm.tsx
Labels: ready
