Repository yaklang/yakit, pull requests merged in 2024-07, with the labels that each got.

#1779 Update grpc.proto
  app/protos/grpc.proto
Labels: ready

#1778 luoluo/fix/poc-input
  app/renderer/src/main/src/pages/securityTool/yakPoC/YakPoC.tsx
Labels: ready

#1783 luoluo/fix/ci
  .github/workflows/yakit-ci.yml
Labels: WIP: work in progress

#1784 fix(suggestion): point range
  app/renderer/src/main/src/utils/monacoSpec/yakCompletionSchema.ts
Labels: ready

#1786 feat(suggestion): highlight signature parameter
  app/renderer/src/main/src/utils/monacoSpec/yakEditor.ts
Labels: ready

#1761 feat(global-config):add dbsavesync config
  app/protos/grpc.proto
  app/renderer/src/main/src/components/configNetwork/ConfigNetworkPage.tsx
Labels: ready

#1787 Song/feat/new home
  app/renderer/src/main/src/assets/icon/colors.tsx
  app/renderer/src/main/src/assets/icon/outline.tsx
  app/renderer/src/main/src/assets/mitm-bg.png
  app/renderer/src/main/src/components/HTTPHistory.module.scss
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/layout/UILayout.tsx
  app/renderer/src/main/src/components/layout/funcDomain.module.scss
  app/renderer/src/main/src/components/layout/uiLayout.module.scss
  app/renderer/src/main/src/defaultConstants/PluginHubPage.ts
  app/renderer/src/main/src/defaultConstants/RiskPage.ts
  app/renderer/src/main/src/pages/assetViewer/EnterpriseReportViewer.module.scss
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.module.scss
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/WebFuzzerPage/WebFuzzerPage.module.scss
  app/renderer/src/main/src/pages/home/Home.tsx
  app/renderer/src/main/src/pages/home/home.module.scss
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/layout/publicMenu/PublicMenu.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.module.scss
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMServerStartForm.tsx
  app/renderer/src/main/src/pages/newHome/NewHome.tsx
  app/renderer/src/main/src/pages/newHome/newHome.module.scss
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/PluginHubList.tsx
  app/renderer/src/main/src/pages/risks/RiskPage.tsx
  app/renderer/src/main/src/pages/risks/VulnerabilityLevelPie/VulnerabilityLevelPie.tsx
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTable.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/routes/publicIcon.tsx
  app/renderer/src/main/src/store/pageInfo.ts
  app/renderer/src/main/src/store/publicMenu.tsx
  app/renderer/src/main/src/utils/eventBus/events/mitm.ts
  app/renderer/src/main/src/utils/eventBus/events/plugins.ts
  app/renderer/src/main/src/utils/eventBus/events/yakitRisk.ts
  app/renderer/src/main/src/yakitGV.ts
Labels: ready

#1785 Luoluo/feat/linux and mac build
  .github/workflows/yakit-ci.yml
  app/main/handlers/upgradeUtil.js
  app/main/handlers/utils/network.js
  app/main/uiOperate/yaklangAndYakit.js
  buildHooks/before_pack.js
  electron-builder.yaml
Labels: ready

#1791 Luoluo/feat/remove risk by title
  app/renderer/src/main/src/pages/assetViewer/PortAssetPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMPluginLogViewer.tsx
  app/renderer/src/main/src/pages/risks/RiskPage.tsx
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTable.tsx
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTableType.d.ts
  app/renderer/src/main/src/pages/risks/YakitRiskTable/utils.ts
  app/renderer/src/main/src/utils/RiskStatsTag.tsx
Labels: ready

#1798 fix: 修复重定向请求问题
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
Labels: ready

#1799 Song/feat/web fuzzer insert label style
  app/renderer/src/main/src/components/yakitUI/YakitEditor/StaticYakitEditor.scss
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerEditorMenu.module.scss
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerEditorMenu.tsx
  app/renderer/src/main/src/pages/payloadManager/newPayload.tsx
  app/renderer/src/main/src/utils/editors.module.scss
Labels: ready

#1806 Refactor/plugin editor
  app/main/utils/clipboard.js
  app/protos/grpc.proto
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/enums/plugin.ts
  app/renderer/src/main/src/enums/website.ts
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerEditorMenu.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/pluginEditor/addYakitPlugin/AddYakitPlugin.module.scss
  app/renderer/src/main/src/pages/pluginEditor/addYakitPlugin/AddYakitPlugin.tsx
  app/renderer/src/main/src/pages/pluginEditor/base.d.ts
  app/renderer/src/main/src/pages/pluginEditor/defaultconstants.ts
  app/renderer/src/main/src/pages/pluginEditor/editorCode/EditorCode.module.scss
  app/renderer/src/main/src/pages/pluginEditor/editorCode/EditorCode.tsx
  app/renderer/src/main/src/pages/pluginEditor/editorInfo/EditorInfo.module.scss
  app/renderer/src/main/src/pages/pluginEditor/editorInfo/EditorInfo.tsx
  app/renderer/src/main/src/pages/pluginEditor/modifyYakitPlugin/ModifyYakitPlugin.module.scss
  app/renderer/src/main/src/pages/pluginEditor/modifyYakitPlugin/ModifyYakitPlugin.tsx
  app/renderer/src/main/src/pages/pluginEditor/pluginEditor/PluginEditor.module.scss
  app/renderer/src/main/src/pages/pluginEditor/pluginEditor/PluginEditor.tsx
  app/renderer/src/main/src/pages/pluginEditor/utils/convert.ts
  app/renderer/src/main/src/pages/pluginEditor/yakitImageTextarea/YakitImageTextarea.module.scss
  app/renderer/src/main/src/pages/pluginEditor/yakitImageTextarea/YakitImageTextarea.tsx
  app/renderer/src/main/src/pages/pluginEditor/yakitImageTextarea/YakitImageTextareaType.d.ts
  app/renderer/src/main/src/pages/pluginHub/hubExtraOperate/HubExtraOperate.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHub/PluginHub.module.scss
  app/renderer/src/main/src/pages/pluginHub/pluginHub/PluginHub.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubDetail/PluginHubDetail.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListLocal.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListOnline.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListOwn.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/PluginHubList.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/funcTemplate.tsx
  app/renderer/src/main/src/pages/pluginHub/utils/grpc.ts
  app/renderer/src/main/src/pages/pluginHub/utils/http.ts
  app/renderer/src/main/src/pages/plugins/baseTemplate.module.scss
  app/renderer/src/main/src/pages/plugins/baseTemplate.tsx
  app/renderer/src/main/src/pages/plugins/builtInData.tsx
  app/renderer/src/main/src/pages/plugins/editDetails/PluginEditDetails.tsx
  app/renderer/src/main/src/pages/plugins/editDetails/utils.tsx
  app/renderer/src/main/src/pages/plugins/log/PluginLogDetail.tsx
  app/renderer/src/main/src/pages/plugins/manage/PluginManageDetail.tsx
  app/renderer/src/main/src/pages/plugins/pluginDebug/PluginDebug.tsx
  app/renderer/src/main/src/pages/plugins/pluginReducer.ts
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/services/swagger/resposeType.ts
  app/renderer/src/main/src/store/tabSubscribe.ts
  app/renderer/src/main/src/utils/eventBus/events/plugins.ts
  app/renderer/src/main/src/yakitGV.ts
Labels: ready, WIP: work in progress

#1811 Yj/fix/optimize/7 8
  app/renderer/src/main/src/assets/icon/colors.tsx
  app/renderer/src/main/src/pages/dynamicControl/DynamicControl.tsx
  app/renderer/src/main/src/pages/loginOperationMenu/AccountAdminPage.tsx
  app/renderer/src/main/src/pages/loginOperationMenu/LicenseAdminPage.tsx
  app/renderer/src/main/src/pages/loginOperationMenu/RoleAdminPage.tsx
  app/renderer/src/main/src/pages/loginOperationMenu/TrustListPage.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListLocal.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListOnline.tsx
  app/renderer/src/main/src/routes/deprecatedMenu.ts
  app/renderer/src/main/src/routes/newRoute.tsx
Labels: ready

#1802 Luoluo/feat/submenu expand
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.module.scss
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContentType.d.ts
  app/renderer/src/main/src/store/pageInfo.ts
Labels: ready

#1809 feat: webfuzzer插入文件支持不填后缀名
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitForm.tsx
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitFormType.d.ts
  app/renderer/src/main/src/pages/fuzzer/InsertFileFuzzTag.tsx
Labels: ready

#1808 feat: 首页劫持跳转问题
  app/main/handlers/mitm.js
  app/renderer/src/main/src/assets/icon/outline.tsx
  app/renderer/src/main/src/pages/home/Home.tsx
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMServerStartForm.tsx
  app/renderer/src/main/src/utils/eventBus/events/mitm.ts
Labels: ready

#1815 Song/feat/web fuzzer max body size
  app/renderer/src/main/src/defaultConstants/HTTPFuzzerPage.ts
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.module.scss
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfigType.d.ts
  app/renderer/src/main/src/pages/fuzzer/components/ShareImportExportData/index.tsx
  app/renderer/src/main/src/pages/plugins/baseTemplate.tsx
  app/renderer/src/main/src/pages/plugins/manage/PluginManageDetail.tsx
Labels: ready

#1794 Luoluo/feat/ee arm64
  multibuilder/electron-builder-ee.yaml
Labels: ready

#1816 style:删除多余的一份样式，两份完全一样
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.module.scss
Labels: ready

#1818 fix: 优化企业版与便携版ci
  .github/workflows/yakit-ci.yml
Labels: ready

#1817 Luoluo/perf/yakit editor
  app/main/handlers/queryHTTPFlow.js
  app/main/handlers/utils/network.js
  app/main/toolsFunc.js
  app/main/utils/nodeFiles.js
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/NewEditorSelectRange.tsx
  app/renderer/src/main/src/components/YakScriptExecResultTable.tsx
  app/renderer/src/main/src/components/playground/PacketListDemo.tsx
  app/renderer/src/main/src/components/playground/spaceengine/SpaceEngineOperator.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditorType.ts
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
  app/renderer/src/main/src/pages/codec/NewCodecUIStore.tsx
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerHistory.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfigType.d.ts
  app/renderer/src/main/src/pages/fuzzer/MatcherAndExtractionCard/MatcherAndExtractionCard.tsx
  app/renderer/src/main/src/pages/fuzzer/WebFuzzerNewEditor/WebFuzzerNewEditor.tsx
  app/renderer/src/main/src/pages/fuzzer/components/HTTPFuzzerPageTable/HTTPFuzzerPageTable.tsx
  app/renderer/src/main/src/pages/fuzzer/components/ShareImportExportData/index.tsx
  app/renderer/src/main/src/pages/httpRequestBuilder/HTTPRequestBuilder.tsx
  app/renderer/src/main/src/pages/invoker/ExecYakScript.tsx
  app/renderer/src/main/src/pages/invoker/ExecutePacketYakScript.tsx
  app/renderer/src/main/src/pages/layout/HeardMenu/HeardMenu.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMHijackedContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMManual.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginHijackContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMFiltersModal.tsx
  app/renderer/src/main/src/pages/packetScanner/HttpFlowViewer.tsx
  app/renderer/src/main/src/pages/packetScanner/PacketScanResult.tsx
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeard.tsx
  app/renderer/src/main/src/pages/plugins/utils.ts
  app/renderer/src/main/src/pages/reverseServer/ReverseTable.tsx
  app/renderer/src/main/src/pages/risks/RiskTable.tsx
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTable.tsx
  app/renderer/src/main/src/pages/yakitStore/viewers/base.tsx
  app/renderer/src/main/src/utils/ConfigMenuItems.tsx
  app/renderer/src/main/src/utils/editors.tsx
  app/renderer/src/main/src/utils/encodec.tsx
Labels: ready

#1832 Yj/fix/optimize/7 12
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/softwareSettings/ProjectManage.module.scss
  app/renderer/src/main/src/pages/softwareSettings/ProjectManage.tsx
  app/renderer/src/main/src/utils/login.tsx
Labels: ready

#1831 Fix/plugin hub list qs
  app/renderer/src/main/src/components/yakChat/chatCS.tsx
  app/renderer/src/main/src/defaultConstants/PluginHubPage.ts
  app/renderer/src/main/src/enums/plugin.ts
  app/renderer/src/main/src/pages/home/Home.tsx
  app/renderer/src/main/src/pages/invoker/schema.ts
  app/renderer/src/main/src/pages/layout/HeardMenu/HeardMenu.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/layout/publicMenu/PublicMenu.tsx
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginLocalList.tsx
  app/renderer/src/main/src/pages/mitm/MITMYakScriptLoader.tsx
  app/renderer/src/main/src/pages/pluginEditor/editorInfo/EditorInfo.tsx
  app/renderer/src/main/src/pages/pluginEditor/pluginEditor/PluginEditor.tsx
  app/renderer/src/main/src/pages/pluginHub/hubExtraOperate/HubExtraOperate.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubDetail/PluginHubDetail.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListLocal.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListOnline.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListOwn.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListRecycle.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/PluginHubList.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/funcTemplate.tsx
  app/renderer/src/main/src/pages/pluginHub/utils/grpc.ts
  app/renderer/src/main/src/pages/plugins/editDetails/PluginEditDetails.tsx
  app/renderer/src/main/src/pages/plugins/group/LocalPluginList.tsx
  app/renderer/src/main/src/pages/plugins/group/OnlinePluginList.tsx
  app/renderer/src/main/src/pages/plugins/local/PluginsLocal.tsx
  app/renderer/src/main/src/pages/plugins/online/PluginsOnline.tsx
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeard.tsx
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeardType.d.ts
  app/renderer/src/main/src/pages/plugins/pluginBatchExecutor/pluginBatchExecutor.tsx
  app/renderer/src/main/src/pages/plugins/singlePluginExecution/SinglePluginExecution.tsx
  app/renderer/src/main/src/pages/plugins/user/PluginUser.tsx
  app/renderer/src/main/src/pages/plugins/utils.ts
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/store/pageInfo.ts
  app/renderer/src/main/src/utils/eventBus/events/plugins.ts
  app/renderer/src/main/src/utils/login.tsx
Labels: ready

#1841 Song/feat/new plugin group mag
  app/assets/导入模板.xlsx
  app/main/api/upload.js
  app/main/handlers/pluginTool.js
  app/main/httpServer.js
  app/protos/grpc.proto
  app/renderer/src/main/src/components/businessUI/FilterPanel/FilterPanel.module.scss
  app/renderer/src/main/src/pages/invoker/schema.ts
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMPage.module.scss
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginHijackContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginLocalList.tsx
  app/renderer/src/main/src/pages/pluginHub/group/PluginGroupDrawer.module.scss
  app/renderer/src/main/src/pages/pluginHub/group/PluginGroupDrawer.tsx
  app/renderer/src/main/src/pages/pluginHub/group/PluginGroupList.module.scss
  app/renderer/src/main/src/pages/pluginHub/group/PluginGroupList.tsx
  app/renderer/src/main/src/pages/pluginHub/group/PluginOperationGroupList.module.scss
  app/renderer/src/main/src/pages/pluginHub/group/PluginOperationGroupList.tsx
  app/renderer/src/main/src/pages/pluginHub/group/UpdateGroupList.module.scss
  app/renderer/src/main/src/pages/pluginHub/group/UpdateGroupList.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListLocal.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListOnline.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/PluginHubList.module.scss
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/PluginHubList.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/funcTemplate.tsx
  app/renderer/src/main/src/pages/plugins/group/LocalPluginList.module.scss
  app/renderer/src/main/src/pages/plugins/group/LocalPluginList.tsx
  app/renderer/src/main/src/pages/plugins/group/OnlinePluginList.module.scss
  app/renderer/src/main/src/pages/plugins/group/OnlinePluginList.tsx
  app/renderer/src/main/src/pages/plugins/group/PluginGroups.module.scss
  app/renderer/src/main/src/pages/plugins/group/PluginGroups.tsx
  app/renderer/src/main/src/pages/plugins/group/PluginListWrap.module.scss
  app/renderer/src/main/src/pages/plugins/group/PluginListWrap.tsx
  app/renderer/src/main/src/pages/plugins/group/PluginLocalGroupList.tsx
  app/renderer/src/main/src/pages/plugins/group/PluginOnlineGroupList.module.scss
  app/renderer/src/main/src/pages/plugins/group/PluginOnlineGroupList.tsx
  app/renderer/src/main/src/pages/plugins/manage/PluginManage.tsx
  app/renderer/src/main/src/pages/plugins/manage/PluginManageDetail.tsx
  app/renderer/src/main/src/pages/plugins/manage/pluginManage.module.scss
  app/renderer/src/main/src/pages/plugins/operator/PluginLocalListDetails/PluginLocalListDetails.tsx
  app/renderer/src/main/src/pages/plugins/pluginBatchExecutor/pluginBatchExecutor.tsx
  app/renderer/src/main/src/pages/plugins/utils.ts
  app/renderer/src/main/src/pages/securityTool/newPortScan/NewPortScan.tsx
  app/renderer/src/main/src/pages/securityTool/yakPoC/YakPoC.tsx
  app/renderer/src/main/src/pages/securityTool/yakPoC/YakPoCType.d.ts
  app/renderer/src/main/src/pages/securityTool/yakPoC/utils.ts
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/utils/eventBus/events/plugins.ts
  app/renderer/src/main/src/yakitGV.ts
Labels: ready

#1834 Luoluo/feature/listener port
  app/main/handlers/listenPort.js
  app/renderer/src/main/package.json
  app/renderer/src/main/src/components/CVXterm.tsx
  app/renderer/src/main/src/components/yakitUI/YakitCVXterm/YakitCVXterm.tsx
  app/renderer/src/main/src/components/yakitUI/YakitXterm/YakitXterm.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitXterm/YakitXterm.tsx
  app/renderer/src/main/src/pages/YakRunner/BottomEditorDetails/TerminalBox/TerminalBox.tsx
  app/renderer/src/main/src/pages/invoker/Terminal.tsx
  app/renderer/src/main/src/pages/pluginHub/hooks/useListenHeight.ts
  app/renderer/src/main/src/pages/reverseShellReceiver/ReverseShellTerminal/ReverseShellTerminal.module.scss
  app/renderer/src/main/src/pages/reverseShellReceiver/ReverseShellTerminal/ReverseShellTerminal.tsx
  app/renderer/src/main/src/pages/reverseShellReceiver/constants.ts
  app/renderer/src/main/src/pages/reverseShellReceiver/shellReceiver.module.scss
  app/renderer/src/main/src/pages/reverseShellReceiver/shellReceiver.tsx
  app/renderer/src/main/src/pages/reverseShellReceiver/utils.ts
  app/renderer/src/main/src/pages/screenRecorder/ScrecorderModal.module.scss
  app/renderer/src/main/src/pages/shellReceiver/CreateShellReceiver.tsx
  app/renderer/src/main/src/pages/shellReceiver/ShellItem.jsx
  app/renderer/src/main/src/pages/shellReceiver/ShellReceiverPage.css
  app/renderer/src/main/src/pages/shellReceiver/ShellReceiverPage.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/utils/basic.tsx
  app/renderer/src/main/src/yakitGV.ts
  app/renderer/src/main/yarn.lock
Labels: ready

#1847 fix:文本域显示数字的时候，icon位置问题
  app/renderer/src/main/src/components/yakitUI/YakitInput/YakitInput.module.scss
Labels: ready

#1845 Song/fix/plugin import
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
  app/renderer/src/main/src/pages/pluginHub/hubExtraOperate/HubExtraOperate.module.scss
  app/renderer/src/main/src/pages/pluginHub/hubExtraOperate/HubExtraOperate.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListLocal.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/PluginHubList.module.scss
  app/renderer/src/main/src/pages/plugins/local/PluginsLocal.tsx
  app/renderer/src/main/src/utils/eventBus/events/plugins.ts
Labels: ready

#1844 Song/feat/performance sample set time
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/layout/UILayout.tsx
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitForm.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitForm.tsx
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitFormType.d.ts
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.tsx
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeard.tsx
  app/renderer/src/main/src/utils/eventBus/events/global.ts
  app/renderer/src/main/src/yakitGV.ts
Labels: ready

#1839 Luoluo/perf/risk page
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTable.module.scss
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTable.tsx
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTableType.d.ts
  app/renderer/src/main/src/pages/risks/schema.ts
  app/renderer/src/main/src/pages/securityTool/newBrute/BruteExecuteParamsDrawer.tsx
  app/renderer/src/main/src/pages/securityTool/newBrute/utils.ts
Labels: ready

#1843 fix: 复制 curl 命令传最新包
  app/renderer/src/main/src/pages/fuzzer/WebFuzzerNewEditor/WebFuzzerNewEditor.tsx
Labels: ready

#1851 Yj/feat/code audit
  app/main/handlers/manageYakScript.js
  app/main/handlers/misc.js
  app/main/handlers/yakRunnerTerminal.js
  app/protos/grpc.proto
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/components/yakitUI/YakitResizeBox/YakitResizeBox.tsx
  app/renderer/src/main/src/pages/YakRunner/BottomEditorDetails/BottomEditorDetails.module.scss
  app/renderer/src/main/src/pages/YakRunner/BottomEditorDetails/BottomEditorDetails.tsx
  app/renderer/src/main/src/pages/YakRunner/BottomEditorDetails/TerminalBox/TerminalBox.module.scss
  app/renderer/src/main/src/pages/YakRunner/BottomEditorDetails/TerminalBox/TerminalBox.tsx
  app/renderer/src/main/src/pages/YakRunner/BottomEditorDetails/TerminalBox/TerminalMap.ts
  app/renderer/src/main/src/pages/YakRunner/CollapseList/CollapseList.module.scss
  app/renderer/src/main/src/pages/YakRunner/CollapseList/CollapseList.tsx
  app/renderer/src/main/src/pages/YakRunner/CollapseList/CollapseListType.ts
  app/renderer/src/main/src/pages/YakRunner/FileTree/FileTree.tsx
  app/renderer/src/main/src/pages/YakRunner/FileTree/FileTreeType.d.ts
  app/renderer/src/main/src/pages/YakRunner/RunnerFileTree/RunnerFileTree.tsx
  app/renderer/src/main/src/pages/YakRunner/RunnerTabs/RunnerTabs.module.scss
  app/renderer/src/main/src/pages/YakRunner/RunnerTabs/RunnerTabs.tsx
  app/renderer/src/main/src/pages/YakRunner/RunnerTabs/RunnerTabsType.d.ts
  app/renderer/src/main/src/pages/YakRunner/YakRunner.tsx
  app/renderer/src/main/src/pages/YakRunner/YakRunnerType.d.ts
  app/renderer/src/main/src/pages/YakRunner/utils.ts
  app/renderer/src/main/src/pages/invoker/Terminal.tsx
  app/renderer/src/main/src/pages/invoker/YakExecutor.css
  app/renderer/src/main/src/pages/invoker/YakExecutor.tsx
  app/renderer/src/main/src/pages/invoker/YakExecutorHistoryTable.tsx
  app/renderer/src/main/src/pages/invoker/YakExecutorParams.tsx
  app/renderer/src/main/src/pages/invoker/YakScriptCreator.scss
  app/renderer/src/main/src/pages/invoker/YakScriptCreator.tsx
  app/renderer/src/main/src/pages/invoker/batch/ExecMessageViewer.tsx
  app/renderer/src/main/src/pages/invoker/batch/YakBatchExecutorLegacy.tsx
  app/renderer/src/main/src/pages/invoker/xtermjs-yak-executor.css
  app/renderer/src/main/src/pages/webShell/WebShellComp.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/utils/editors.tsx
  app/renderer/src/main/src/utils/eventBus/events/yakRunner.ts
  app/renderer/src/main/src/yakitGV.ts
Labels: ready

#1855 Feature/plugin mitm params and upload
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/layout/LocalEngine/LocalEngine.tsx
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitFormType.d.ts
  app/renderer/src/main/src/enums/plugin.ts
  app/renderer/src/main/src/pages/pluginEditor/editorCode/EditorCode.tsx
  app/renderer/src/main/src/pages/pluginEditor/pluginEditor/PluginEditor.tsx
  app/renderer/src/main/src/pages/pluginEditor/utils/convert.ts
  app/renderer/src/main/src/pages/pluginHub/hubExtraOperate/HubExtraOperate.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHub/PluginHub.module.scss
  app/renderer/src/main/src/pages/pluginHub/pluginHub/PluginHub.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubDetail/PluginHubDetail.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListLocal.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/funcTemplate.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginUploadModal/PluginUploadModal.module.scss
  app/renderer/src/main/src/pages/pluginHub/pluginUploadModal/PluginUploadModal.tsx
  app/renderer/src/main/src/pages/plugins/funcTemplate.tsx
  app/renderer/src/main/src/pages/plugins/funcTemplateType.ts
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeard.tsx
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/PluginExecuteExtraParams.module.scss
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/PluginExecuteExtraParams.tsx
  app/renderer/src/main/src/pages/plugins/pluginDebug/PluginDebug.tsx
  app/renderer/src/main/src/pages/plugins/utils.ts
Labels: ready

#1857 Song/fix/project mag
  app/main/handlers/project.js
  app/protos/grpc.proto
  app/renderer/src/main/src/components/configNetwork/ConfigNetworkPage.tsx
  app/renderer/src/main/src/components/layout/UILayout.tsx
  app/renderer/src/main/src/pages/softwareSettings/ProjectManage.tsx
  app/renderer/src/main/src/utils/ConfigSystemProxy.tsx
Labels: ready

#1856 Song/feat/mitmdown stream agent to web fuzzer
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/HTTPHistory.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMHijackedContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.tsx
  app/renderer/src/main/src/utils/editors.tsx
Labels: ready

#1859 luoluo/fix/monaco-cursor
  app/renderer/src/main/package.json
  app/renderer/src/main/yarn.lock
Labels: ready

#1862 Song/feat/switch plugin type pop
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitForm.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitForm.tsx
  app/renderer/src/main/src/pages/pluginEditor/editorInfo/EditorInfo.tsx
Labels: ready
