Repository yaklang/yakit, pull requests merged in 2024-03, with the labels that each got.

#1460 Yj/fix/history export
  app/main/httpServer.js
  app/renderer/src/main/package.json
  app/renderer/src/main/src/NewApp.tsx
  app/renderer/src/main/src/components/DataExport/DataExport.tsx
  app/renderer/src/main/src/components/DataExport/toExcel.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/yakChat/chatCS.tsx
  app/renderer/src/main/src/components/yakChat/icon.tsx
  app/renderer/src/main/src/pages/newHome/NewHome.tsx
  app/renderer/src/main/src/pages/newHome/newHome.module.scss
  app/renderer/src/main/src/pages/plugins/funcTemplate.module.scss
  app/renderer/src/main/src/pages/plugins/utils.ts
  app/renderer/src/main/src/utils/visitorsStatistics.tsx
  app/renderer/src/main/yarn.lock
  build/yakit_build.nsh
  package.json
  yarn.lock
Labels: ready

#1466 fix: 导出优化
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/codec/NewCodec.tsx
Labels: ready

#1457 Song/feat/plugin group
  app/main/handlers/pluginTool.js
  app/protos/grpc.proto
  app/renderer/src/main/src/components/businessUI/FilterPanel/FilterPanel.tsx
  app/renderer/src/main/src/components/businessUI/FilterPanel/FilterPanelType.ts
  app/renderer/src/main/src/pages/invoker/schema.ts
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginHijackContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginLocalList.tsx
  app/renderer/src/main/src/pages/pluginDebugger/PluginDebuggerPage.tsx
  app/renderer/src/main/src/pages/plugins/builtInData.tsx
  app/renderer/src/main/src/pages/plugins/funcTemplate.tsx
  app/renderer/src/main/src/pages/plugins/funcTemplateType.ts
  app/renderer/src/main/src/pages/plugins/group/LocalPluginList.module.scss
  app/renderer/src/main/src/pages/plugins/group/LocalPluginList.tsx
  app/renderer/src/main/src/pages/plugins/group/OnlinePluginList.module.scss
  app/renderer/src/main/src/pages/plugins/group/OnlinePluginList.tsx
  app/renderer/src/main/src/pages/plugins/group/PluginGroupList.module.scss
  app/renderer/src/main/src/pages/plugins/group/PluginGroupList.tsx
  app/renderer/src/main/src/pages/plugins/group/PluginGroups.module.scss
  app/renderer/src/main/src/pages/plugins/group/PluginGroups.tsx
  app/renderer/src/main/src/pages/plugins/group/PluginListWrap.module.scss
  app/renderer/src/main/src/pages/plugins/group/PluginListWrap.tsx
  app/renderer/src/main/src/pages/plugins/group/PluginLocalGroupList.module.scss
  app/renderer/src/main/src/pages/plugins/group/PluginLocalGroupList.tsx
  app/renderer/src/main/src/pages/plugins/group/PluginOnlineGroupList.module.scss
  app/renderer/src/main/src/pages/plugins/group/PluginOnlineGroupList.tsx
  app/renderer/src/main/src/pages/plugins/group/UpdateGroupList.module.scss
  app/renderer/src/main/src/pages/plugins/group/UpdateGroupList.tsx
  app/renderer/src/main/src/pages/plugins/local/PluginsLocal.module.scss
  app/renderer/src/main/src/pages/plugins/local/PluginsLocal.tsx
  app/renderer/src/main/src/pages/plugins/local/PluginsLocalDetail.tsx
  app/renderer/src/main/src/pages/plugins/local/PluginsLocalType.d.ts
  app/renderer/src/main/src/pages/plugins/manage/PluginManage.tsx
  app/renderer/src/main/src/pages/plugins/manage/PluginManageDetail.tsx
  app/renderer/src/main/src/pages/plugins/online/PluginsOnline.tsx
  app/renderer/src/main/src/pages/plugins/online/PluginsOnlineDetail.tsx
  app/renderer/src/main/src/pages/plugins/utils.ts
  app/renderer/src/main/src/pages/simpleDetect/SimpleDetect.tsx
  app/renderer/src/main/src/pages/yakitStore/PluginOperator.tsx
  app/renderer/src/main/src/pages/yakitStore/YakitStorePage.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/services/swagger/resposeType.ts
  app/renderer/src/main/src/utils/eventBus/events/plugins.ts
  app/renderer/src/main/src/yakitGV.ts
Labels: ready

#1455 feat(nsis_build): set default install path
  build/yakit_build.nsh
  electron-builder.yaml
  multibuilder/electron-builder-ee.yaml
  multibuilder/electron-builder-se.yaml
Labels: ready

#1464 fix: 修复代理主机&端口初始默认值问题
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMServerStartForm.tsx
Labels: ready

#1461 Yj/feature/yakit download/2 29
  app/main/filePath.js
  app/main/handlers/upgradeUtil.js
  app/main/uiOperate/hardware.js
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/layout/UILayout.tsx
  app/renderer/src/main/src/components/layout/update/UpdateYakitAndYaklang.tsx
Labels: ready

#1468 feat: 插件商店屏蔽插件组
  app/renderer/src/main/src/pages/plugins/online/PluginsOnlineDetail.tsx
Labels: ready

#1456 Luoluo/feature/new po c
  app/main/handlers/pluginTool.js
  app/main/ipc.js
  app/main/utils/nodeFiles.js
  app/renderer/src/main/src/assets/icon/colors.tsx
  app/renderer/src/main/src/components/RollingLoadList/RollingLoadList.tsx
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitForm.tsx
  app/renderer/src/main/src/pages/assetViewer/PortTable/PortTableType.d.ts
  app/renderer/src/main/src/pages/invoker/batch/YakBatchExecutors.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.module.scss
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/plugins/baseTemplate.module.scss
  app/renderer/src/main/src/pages/plugins/baseTemplate.tsx
  app/renderer/src/main/src/pages/plugins/baseTemplateType.ts
  app/renderer/src/main/src/pages/plugins/local/LocalPluginExecute.tsx
  app/renderer/src/main/src/pages/plugins/operator/expandAndRetract/ExpandAndRetract.module.scss
  app/renderer/src/main/src/pages/plugins/operator/expandAndRetract/ExpandAndRetract.tsx
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeard.tsx
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeardType.d.ts
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/PluginExecuteResult.module.scss
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/PluginExecuteResult.tsx
  app/renderer/src/main/src/pages/plugins/pluginBatchExecutor/pluginBatchExecutor.tsx
  app/renderer/src/main/src/pages/plugins/plugins.scss
  app/renderer/src/main/src/pages/plugins/user/PluginUserDetail.tsx
  app/renderer/src/main/src/pages/plugins/utils.ts
  app/renderer/src/main/src/pages/securityTool/yakPoC/yakPoC.module.scss
  app/renderer/src/main/src/pages/securityTool/yakPoC/yakPoC.tsx
  app/renderer/src/main/src/pages/securityTool/yakPoC/yakPoCType.d.ts
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/store/pageInfo.ts
Labels: ready

#1470 feat: engine & render error info collection log
  app/main/errorCollection.js
  app/main/filePath.js
  app/main/handlers/engineStatus.js
  app/main/handlers/misc.js
  app/main/index.js
  app/main/ipc.js
  app/main/localCache.js
  app/main/newsTips/index.js
  app/main/newsTips/preload.js
  app/main/toolsFunc.js
  app/renderer/src/main/src/NewApp.tsx
  arm-electron-builder.yaml
Labels: ready

#1472 Luoluo/feature/new plugin linkage
  app/protos/grpc.proto
  app/renderer/src/main/src/components/configNetwork/ConfigNetworkPage.tsx
  app/renderer/src/main/src/components/configNetwork/ThirdPartyApplicationConfig.tsx
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/yakitUI/YakitAutoComplete/YakitAutoComplete.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginLocalList.tsx
  app/renderer/src/main/src/pages/plugins/baseTemplate.module.scss
  app/renderer/src/main/src/pages/plugins/baseTemplate.tsx
  app/renderer/src/main/src/pages/plugins/baseTemplateType.ts
  app/renderer/src/main/src/pages/plugins/funcTemplate.module.scss
  app/renderer/src/main/src/pages/plugins/local/LocalPluginExecute.tsx
  app/renderer/src/main/src/pages/plugins/local/PluginsLocalDetail.tsx
  app/renderer/src/main/src/pages/plugins/local/PluginsLocalType.d.ts
  app/renderer/src/main/src/pages/plugins/manage/PluginManageDetail.tsx
  app/renderer/src/main/src/pages/plugins/manage/pluginManage.module.scss
  app/renderer/src/main/src/pages/plugins/operator/expandAndRetract/ExpandAndRetract.module.scss
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeard.tsx
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeardType.d.ts
  app/renderer/src/main/src/pages/plugins/pluginBatchExecutor/pluginBatchExecutor.tsx
  app/renderer/src/main/src/pages/plugins/plugins.scss
  app/renderer/src/main/src/pages/plugins/singlePluginExecution/SinglePluginExecution.module.scss
  app/renderer/src/main/src/pages/plugins/singlePluginExecution/SinglePluginExecution.tsx
  app/renderer/src/main/src/pages/plugins/utils.ts
  app/renderer/src/main/src/pages/spaceEngine/SpaceEnginePage.module.scss
  app/renderer/src/main/src/pages/spaceEngine/SpaceEnginePage.tsx
  app/renderer/src/main/src/pages/spaceEngine/ZoomeyeHelp.tsx
  app/renderer/src/main/src/pages/spaceEngine/fingerprint.png
  app/renderer/src/main/src/pages/yakitStore/YakitStorePage.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
Labels: ready

#1474 Yj/fix/chat cs 3 1
  app/renderer/src/main/src/components/yakChat/chatCS.module.scss
  app/renderer/src/main/src/components/yakChat/chatCS.tsx
  app/renderer/src/main/src/components/yakChat/chatCSType.ts
Labels: ready

#1475 fix: webFuzzerId显示问题
  app/renderer/src/main/src/pages/fuzzer/components/HTTPFuzzerPageTable/HTTPFuzzerPageTable.tsx
Labels: ready

#1476 feat: webFuzzer历史记录没有默认打开全部，有历史记录关闭全部
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerHistory.tsx
Labels: ready

#1477 Song/feat/web fuzzer batch target
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfigType.d.ts
  app/renderer/src/main/src/pages/fuzzer/components/ShareImportExportData/index.tsx
Labels: ready

#1478 Song/feat/simple detect weak password
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginLocalList.tsx
  app/renderer/src/main/src/pages/plugins/baseTemplate.tsx
  app/renderer/src/main/src/pages/plugins/baseTemplateType.ts
  app/renderer/src/main/src/pages/plugins/local/PluginsLocalDetail.tsx
  app/renderer/src/main/src/pages/plugins/manage/PluginManageDetail.tsx
  app/renderer/src/main/src/pages/plugins/online/PluginsOnlineDetail.tsx
  app/renderer/src/main/src/pages/plugins/utils.ts
  app/renderer/src/main/src/pages/simpleDetect/SimpleDetect.tsx
Labels: ready

#1482 feat：企业版&便携版屏蔽引擎更新
  app/renderer/src/main/src/components/basics/YakitLoading.tsx
Labels: ready

#1483 fix: 修复编辑器废弃横线不消失问题
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
Labels: ready

#1485 Yj/fix/some bug/03 06
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditorType.ts
  app/renderer/src/main/src/components/yakitUI/YakitEditor/contextMenus.tsx
  app/renderer/src/main/src/pages/codec/NewCodec.tsx
  app/renderer/src/main/src/pages/dnslog/DNSLogPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/layout/publicMenu/MenuDNSLog.module.scss
  app/renderer/src/main/src/pages/layout/publicMenu/MenuDNSLog.tsx
Labels: ready

#1487 fix: 修复 webfuzzer 全部查看历史记录问题
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerHistory.tsx
Labels: ready

#1497 Song/feat/web fuzzer add fields
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfigType.d.ts
  app/renderer/src/main/src/pages/fuzzer/components/ShareImportExportData/index.tsx
Labels: ready

#1500 fix: 反连服务器生成的反连地址带上类名
  app/renderer/src/main/src/pages/reverseServer/NewReverseServerPage.tsx
Labels: ready

#1499 Song/fix/plugin group refresh
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginLocalList.tsx
  app/renderer/src/main/src/pages/plugins/group/OnlinePluginList.tsx
  app/renderer/src/main/src/pages/plugins/group/PluginGroups.tsx
  app/renderer/src/main/src/pages/plugins/group/PluginLocalGroupList.tsx
  app/renderer/src/main/src/pages/plugins/group/PluginOnlineGroupList.tsx
  app/renderer/src/main/src/pages/plugins/manage/PluginManage.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/utils/eventBus/events/plugins.ts
Labels: ready

#1498 Song/feat/web socket editor
  app/protos/grpc.proto
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.module.scss
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContentType.d.ts
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMHijackedContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMManual.tsx
  app/renderer/src/main/src/pages/websocket/HTTPFlowForWebsocketViewer.module.scss
  app/renderer/src/main/src/pages/websocket/HTTPFlowForWebsocketViewer.tsx
  app/renderer/src/main/src/pages/websocket/WebsocketClientOperator.tsx
  app/renderer/src/main/src/pages/websocket/WebsocketFuzzer.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/utils/editors.tsx
Labels: ready

#1501 fix: 分享排除批量目标
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
Labels: ready

#1503 Song/feat/web fuzzer add animation
  app/renderer/src/main/config-overrides.js
  app/renderer/src/main/package.json
  app/renderer/src/main/src/assets/blasting-count.mp4
  app/renderer/src/main/src/assets/blasting-id.mp4
  app/renderer/src/main/src/assets/blasting-pwd.mp4
  app/renderer/src/main/src/assets/sequence.mp4
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.module.scss
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.module.scss
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/types/video.d.ts
Labels: ready

#1506 Yj/fix/reduce loop
  app/protos/grpc.proto
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/layout/GlobalState.tsx
  app/renderer/src/main/src/utils/duplex/duplex.tsx
  app/renderer/src/main/src/utils/eventBus/eventBus.ts
  app/renderer/src/main/src/utils/eventBus/events/refreshData.ts
Labels: ready

#1507 feat: 注释掉新加字段
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.tsx
Labels: ready

#1502 [Refactor] debugScript support pass PluginName
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeard.tsx
  app/renderer/src/main/src/pages/plugins/pluginDebug/PluginDebug.tsx
  app/renderer/src/main/src/pages/plugins/utils.ts
Labels: ready, WIP: work in progress

#1508 [Fix] linkPlugin use allCheck not select length
  app/renderer/src/main/src/pages/plugins/singlePluginExecution/SinglePluginExecution.tsx
Labels: ready

#1513 [Fix] debugScript skip False parameter
  app/renderer/src/main/src/pages/plugins/editDetails/utils.tsx
  app/renderer/src/main/src/pages/plugins/pluginDebug/PluginDebug.module.scss
  app/renderer/src/main/src/utils/tool.ts
Labels: WIP: work in progress

#1511 fix: scrollToIndex拼接随机值处理跳转失效问题
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResizeType.d.ts
Labels: ready

#1512 Song/feat/mitm tabs switch
  app/renderer/src/main/src/components/HTTPHistory.module.scss
  app/renderer/src/main/src/pages/mitm/MITMPage.module.scss
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMHijackedContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginHijackContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.module.scss
  app/renderer/src/main/src/yakitGV.ts
Labels: ready

#1510 feat: 表格颜色标记背景颜色调整
  app/renderer/src/main/src/assets/global.scss
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.module.scss
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
  app/renderer/src/main/src/yakitUI.scss
Labels: ready

#1523 Song/feat/add fuzz tag
  app/renderer/src/main/src/pages/layout/publicMenu/MenuCodec.module.scss
  app/renderer/src/main/src/pages/layout/publicMenu/MenuCodec.tsx
  app/renderer/src/main/src/pages/layout/publicMenu/PublicMenu.module.scss
Labels: ready

#1525 feat：MutateMethods传值修改
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.tsx
Labels: ready

#1524 Song/feat/editor beautification
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/components/HTTPFuzzerPageTable/HTTPFuzzerPageTable.tsx
  app/renderer/src/main/src/utils/editors.tsx
  app/renderer/src/main/src/utils/prettifyPacket.tsx
  app/renderer/src/main/src/yakitGV.ts
Labels: ready

#1496 Luoluo/feature/new port scan
  app/protos/grpc.proto
  app/renderer/src/main/src/assets/icon/outline.tsx
  app/renderer/src/main/src/components/configNetwork/ConfigNetworkPage.tsx
  app/renderer/src/main/src/components/yakChat/chatCS.tsx
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitForm.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitForm.tsx
  app/renderer/src/main/src/components/yakitUI/YakitInputNumber/YakitInputNumber.module.scss
  app/renderer/src/main/src/pages/assetViewer/PortTable/PortTable.tsx
  app/renderer/src/main/src/pages/invoker/batch/BatchExecutorPageEx.tsx
  app/renderer/src/main/src/pages/plugins/funcTemplate.tsx
  app/renderer/src/main/src/pages/plugins/funcTemplateType.ts
  app/renderer/src/main/src/pages/plugins/group/LocalPluginList.tsx
  app/renderer/src/main/src/pages/plugins/local/PluginsLocal.tsx
  app/renderer/src/main/src/pages/plugins/local/PluginsLocalDetail.tsx
  app/renderer/src/main/src/pages/plugins/operator/PluginLocalListDetails/PluginLocalListDetails.module.scss
  app/renderer/src/main/src/pages/plugins/operator/PluginLocalListDetails/PluginLocalListDetails.tsx
  app/renderer/src/main/src/pages/plugins/operator/PluginLocalListDetails/PluginLocalListDetailsType.d.ts
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeard.module.scss
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeard.tsx
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/PluginExecuteResult.tsx
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/PluginExecuteResultType.d.ts
  app/renderer/src/main/src/pages/plugins/pluginBatchExecutor/PluginBatchExecutor.module.scss
  app/renderer/src/main/src/pages/plugins/pluginBatchExecutor/pluginBatchExecutor.tsx
  app/renderer/src/main/src/pages/plugins/pluginDebug/PluginDebug.tsx
  app/renderer/src/main/src/pages/plugins/singlePluginExecution/SinglePluginExecution.module.scss
  app/renderer/src/main/src/pages/plugins/singlePluginExecution/SinglePluginExecution.tsx
  app/renderer/src/main/src/pages/plugins/utils.ts
  app/renderer/src/main/src/pages/portscan/CreateReport.tsx
  app/renderer/src/main/src/pages/portscan/PortScanPage.tsx
  app/renderer/src/main/src/pages/securityTool/newPortScan/newPortScan.module.scss
  app/renderer/src/main/src/pages/securityTool/newPortScan/newPortScan.tsx
  app/renderer/src/main/src/pages/securityTool/newPortScan/newPortScanExtraParamsDrawer.module.scss
  app/renderer/src/main/src/pages/securityTool/newPortScan/newPortScanExtraParamsDrawer.tsx
  app/renderer/src/main/src/pages/securityTool/newPortScan/newPortScanType.d.ts
  app/renderer/src/main/src/pages/securityTool/newPortScan/utils.ts
  app/renderer/src/main/src/pages/securityTool/securityTool.scss
  app/renderer/src/main/src/pages/securityTool/yakPoC/yakPoC.module.scss
  app/renderer/src/main/src/pages/securityTool/yakPoC/yakPoC.tsx
  app/renderer/src/main/src/pages/simpleDetect/SimpleDetect.tsx
  app/renderer/src/main/src/pages/spaceEngine/utils.ts
  app/renderer/src/main/src/pages/yakitStore/PluginOperator.scss
  app/renderer/src/main/src/pages/yakitStore/PluginOperator.tsx
  app/renderer/src/main/src/pages/yakitStore/YakitStorePage.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/theme/componentsTheme/form.scss
  app/renderer/src/main/src/utils/codeViewer.tsx
Labels: ready

#1518 Feature/plugin log
  app/renderer/src/main/src/components/ConfigPrivateDomain/ConfigPrivateDomain.tsx
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/yakitUI/YakitCollapseText/YakitCollapseText.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitCollapseText/YakitCollapseText.tsx
  app/renderer/src/main/src/components/yakitUI/YakitCollapseText/YakitCollapseTextType.d.ts
  app/renderer/src/main/src/components/yakitUI/YakitRoundCornerTag/YakitRoundCornerTag.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitRoundCornerTag/YakitRoundCornerTag.tsx
  app/renderer/src/main/src/components/yakitUI/YakitRoundCornerTag/YakitRoundCornerTagType.d.ts
  app/renderer/src/main/src/components/yakitUI/YakitTimeLineList/YakitTimeLineList.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitTimeLineList/YakitTimeLineList.tsx
  app/renderer/src/main/src/components/yakitUI/YakitTimeLineList/YakitTimeLineListType.d.ts
  app/renderer/src/main/src/components/yakitUI/YakitTimeLineList/icon.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/plugins/baseTemplateType.ts
  app/renderer/src/main/src/pages/plugins/editDetails/PluginLogDetail.tsx
  app/renderer/src/main/src/pages/plugins/local/PluginsLocalDetail.module.scss
  app/renderer/src/main/src/pages/plugins/local/PluginsLocalDetail.tsx
  app/renderer/src/main/src/pages/plugins/local/PluginsLocalType.d.ts
  app/renderer/src/main/src/pages/plugins/log/PluginLog.module.scss
  app/renderer/src/main/src/pages/plugins/log/PluginLog.tsx
  app/renderer/src/main/src/pages/plugins/log/PluginLogDetail.module.scss
  app/renderer/src/main/src/pages/plugins/log/PluginLogDetail.tsx
  app/renderer/src/main/src/pages/plugins/log/PluginLogDetailType.d.ts
  app/renderer/src/main/src/pages/plugins/log/PluginLogType.d.ts
  app/renderer/src/main/src/pages/plugins/log/icon.tsx
  app/renderer/src/main/src/pages/plugins/manage/PluginManageDetail.tsx
  app/renderer/src/main/src/pages/plugins/manage/pluginManage.module.scss
  app/renderer/src/main/src/pages/plugins/online/PluginsOnlineDetail.module.scss
  app/renderer/src/main/src/pages/plugins/online/PluginsOnlineDetail.tsx
  app/renderer/src/main/src/pages/plugins/pluginDebug/PluginDebug.tsx
  app/renderer/src/main/src/pages/plugins/pluginDebug/PluginDebugType.d.ts
  app/renderer/src/main/src/pages/plugins/user/PluginUserDetail.module.scss
  app/renderer/src/main/src/pages/plugins/user/PluginUserDetail.tsx
  app/renderer/src/main/src/pages/plugins/utils.ts
  app/renderer/src/main/src/pages/yakitStore/YakitPluginOnlineJournal/YakitPluginJournalDetails.scss
  app/renderer/src/main/src/pages/yakitStore/YakitPluginOnlineJournal/YakitPluginJournalDetails.tsx
  app/renderer/src/main/src/pages/yakitStore/YakitPluginOnlineJournal/YakitPluginOnlineJournal.scss
  app/renderer/src/main/src/pages/yakitStore/YakitPluginOnlineJournal/YakitPluginOnlineJournal.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/services/swagger/resposeType.ts
  app/renderer/src/main/src/theme/themeify.scss
  app/renderer/src/main/src/types/http-api.d.ts
Labels: ready

#1520 Luoluo/feature/poc keyword group
  app/protos/grpc.proto
  app/renderer/src/main/src/components/yakChat/chatCS.tsx
  app/renderer/src/main/src/components/yakitUI/YakitRadioButtons/YakitRadioButtons.module.scss
  app/renderer/src/main/src/hook/useHoldBatchGRPCStream/useHoldBatchGRPCStream.ts
  app/renderer/src/main/src/hook/useHoldBatchGRPCStream/useHoldBatchGRPCStreamType.d.ts
  app/renderer/src/main/src/hook/useHoldGRPCStream/useHoldGRPCStreamType.d.ts
  app/renderer/src/main/src/pages/invoker/schema.ts
  app/renderer/src/main/src/pages/plugins/baseTemplate.tsx
  app/renderer/src/main/src/pages/plugins/baseTemplateType.ts
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeard.module.scss
  app/renderer/src/main/src/pages/plugins/pluginBatchExecutor/PluginBatchExecuteExtraParams.tsx
  app/renderer/src/main/src/pages/plugins/pluginBatchExecutor/PluginBatchExecutor.module.scss
  app/renderer/src/main/src/pages/plugins/pluginBatchExecutor/pluginBatchExecutor.tsx
  app/renderer/src/main/src/pages/plugins/plugins.scss
  app/renderer/src/main/src/pages/plugins/utils.ts
  app/renderer/src/main/src/pages/securityTool/securityTool.scss
  app/renderer/src/main/src/pages/securityTool/yakPoC/utils.ts
  app/renderer/src/main/src/pages/securityTool/yakPoC/yakPoC.module.scss
  app/renderer/src/main/src/pages/securityTool/yakPoC/yakPoC.tsx
  app/renderer/src/main/src/pages/securityTool/yakPoC/yakPoCType.d.ts
  app/renderer/src/main/src/store/pageInfo.ts
  app/renderer/src/main/src/yakitGV.ts
Labels: ready

#1540 style: 插件组list给最大高度
  app/renderer/src/main/src/pages/mitm/MITMPage.module.scss
Labels: ready

#1541 luoluo/fix/webFuzzer-group
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
Labels: ready

#1533 luoluo/feature/poc-add-id-scan
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/playground/hybrid/HybridScanDemo.tsx
  app/renderer/src/main/src/models/HTTPRequestBuilder.tsx
  app/renderer/src/main/src/pages/httpRequestBuilder/HTTPRequestBuilder.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/packetScanner/DefaultPacketScanGroup.tsx
  app/renderer/src/main/src/pages/packetScanner/PacketScanner.tsx
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeard.tsx
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeardType.d.ts
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/PluginExecuteExtraParams.tsx
  app/renderer/src/main/src/pages/plugins/pluginBatchExecutor/PluginBatchExecuteExtraParams.tsx
  app/renderer/src/main/src/pages/plugins/pluginBatchExecutor/pluginBatchExecutor.tsx
  app/renderer/src/main/src/pages/plugins/utils.ts
  app/renderer/src/main/src/pages/securityTool/newPortScan/NewPortScan.module.scss
  app/renderer/src/main/src/pages/securityTool/newPortScan/NewPortScan.tsx
  app/renderer/src/main/src/pages/securityTool/newPortScan/NewPortScanExtraParamsDrawer.module.scss
  app/renderer/src/main/src/pages/securityTool/newPortScan/NewPortScanExtraParamsDrawer.tsx
  app/renderer/src/main/src/pages/securityTool/newPortScan/NewPortScanType.d.ts
  app/renderer/src/main/src/pages/securityTool/newPortScan/utils.ts
  app/renderer/src/main/src/pages/securityTool/yakPoC/YakPoC.module.scss
  app/renderer/src/main/src/pages/securityTool/yakPoC/YakPoC.tsx
  app/renderer/src/main/src/pages/securityTool/yakPoC/YakPoCType.d.ts
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/store/pageInfo.ts
Labels: ready

#1543 pref: 数据包详情参数过长给省略号加提示
  app/renderer/src/main/src/components/FuzzableParamList.tsx
  app/renderer/src/main/src/components/HTTPFlowExtractedDataTable.tsx
Labels: ready

#1544 Song/fix/web fuzzer analyzing
  app/renderer/src/main/src/assets/blasting-count.mp4
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.tsx
  app/renderer/src/main/src/pages/fuzzer/WebFuzzerPage/WebFuzzerPage.tsx
Labels: ready

#1545 Song/feat/cache data structure migration
  app/renderer/src/main/src/components/ConfigPrivateDomain/ConfigPrivateDomain.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/baseTemplate/BaseTags.scss
  app/renderer/src/main/src/components/baseTemplate/BaseTags.tsx
  app/renderer/src/main/src/components/baseTemplate/FormItemUtil.tsx
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/layout/UILayout.tsx
  app/renderer/src/main/src/components/yakitUI/YakitAutoComplete/YakitAutoComplete.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitAutoComplete/YakitAutoComplete.tsx
  app/renderer/src/main/src/components/yakitUI/YakitAutoComplete/YakitAutoCompleteType.d.ts
  app/renderer/src/main/src/components/yakitUI/YakitSelect/YakitSelect.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitSelect/YakitSelect.tsx
  app/renderer/src/main/src/components/yakitUI/YakitSelect/YakitSelectType.d.ts
  app/renderer/src/main/src/components/yakitUI/utils.ts
  app/renderer/src/main/src/pages/SelectUpload.tsx
  app/renderer/src/main/src/pages/cve/CVETable.tsx
  app/renderer/src/main/src/pages/dnslog/DNSLogPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.tsx
  app/renderer/src/main/src/pages/invoker/batch/QueryYakScriptParam.tsx
  app/renderer/src/main/src/pages/loginOperationMenu/AccountAdminPage.tsx
  app/renderer/src/main/src/pages/loginOperationMenu/LicenseAdminPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMChromeLauncher.tsx
  app/renderer/src/main/src/pages/mitm/MITMRule/MITMRule.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMServerStartForm.tsx
  app/renderer/src/main/src/pages/payloadGenerater/NewJavaPayloadPage.tsx
  app/renderer/src/main/src/pages/reverseServer/ReverseServer_New.tsx
  app/renderer/src/main/src/pages/reverseServer/ReverseTable.tsx
  app/renderer/src/main/src/pages/yakitStore/YakitPluginInfoOnline/EditOnlinePluginDetails.tsx
  app/renderer/src/main/src/pages/yakitStore/YakitStorePage.tsx
  app/renderer/src/main/src/utils/SelectItem/index.tsx
  app/renderer/src/main/src/utils/inputUtil.tsx
  app/renderer/src/main/src/utils/timeInterval.tsx
  app/renderer/src/main/src/utils/timeRange.tsx
  app/renderer/src/main/src/yakitGV.ts
Labels: ready

#1548 Yj/fix/some bug/3 14
  app/main/api/upload.js
  app/main/handlers/userInfo.js
  app/renderer/src/main/src/NewApp.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
  app/renderer/src/main/src/pages/SelectUpload.tsx
  app/renderer/src/main/src/pages/invoker/fromPacketToYakCode.ts
  app/renderer/src/main/src/pages/plugins/group/OnlinePluginList.module.scss
  app/renderer/src/main/src/pages/plugins/group/OnlinePluginList.tsx
  app/renderer/src/main/src/pages/plugins/group/PluginOnlineGroupList.tsx
  app/renderer/src/main/src/pages/softwareSettings/ProjectManage.tsx
  app/renderer/src/main/src/utils/editors.tsx
  app/renderer/src/main/src/utils/eventBus/events/plugins.ts
Labels: ready

#1534 create event emits for fetching yak version
  app/main/filePath.js
  app/main/handlers/upgradeUtil.js
  app/renderer/src/main/src/NewApp.tsx
  app/renderer/src/main/src/components/baseTemplate/BaseTags.tsx
  app/renderer/src/main/src/components/basics/YakitLoading.tsx
  app/renderer/src/main/src/components/layout/LocalEngineCheck/LocalEngineCheck.tsx
  app/renderer/src/main/src/components/layout/UILayout.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/index.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/store/pageInfo.ts
Labels: ready
