Repository yaklang/yakit, pull requests merged in 2024-09, with the labels that each got.

#1966 Luoluo/feature/local plugin execute log
  app/renderer/src/main/package.json
  app/renderer/src/main/src/NewApp.tsx
  app/renderer/src/main/src/assets/global.scss
  app/renderer/src/main/src/assets/icon/colors.tsx
  app/renderer/src/main/src/components/HTTPFlowRiskViewer.tsx
  app/renderer/src/main/src/components/businessUI/PluginTabs/PluginTabs.module.scss
  app/renderer/src/main/src/components/businessUI/PluginTabs/PluginTabs.tsx
  app/renderer/src/main/src/components/yakitUI/YakitTag/YakitTag.tsx
  app/renderer/src/main/src/components/yakitUI/YakitTag/YakitTagType.d.ts
  app/renderer/src/main/src/hook/useHoldGRPCStream/useHoldGRPCStream.ts
  app/renderer/src/main/src/hook/useHoldGRPCStream/useHoldGRPCStreamType.d.ts
  app/renderer/src/main/src/pages/globalVariable.ts
  app/renderer/src/main/src/pages/graph/base.tsx
  app/renderer/src/main/src/pages/invoker/LogCharts/LogCharts.module.scss
  app/renderer/src/main/src/pages/invoker/LogCharts/LogCharts.tsx
  app/renderer/src/main/src/pages/invoker/LogCharts/WordCloudCharts.tsx
  app/renderer/src/main/src/pages/invoker/LogCharts/chartsOption.tsx
  app/renderer/src/main/src/pages/invoker/YakitLogFormatter.module.scss
  app/renderer/src/main/src/pages/invoker/YakitLogFormatter.tsx
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/LocalPluginLog.module.scss
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/LocalPluginLog.tsx
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/PluginExecuteResult.module.scss
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/PluginExecuteResult.tsx
  app/renderer/src/main/src/pages/yakitStore/viewers/base.tsx
  app/renderer/src/main/src/utils/basic.tsx
  app/renderer/src/main/src/utils/tool.ts
  app/renderer/src/main/src/yakitUI.scss
  app/renderer/src/main/yarn.lock
Labels: WIP: work in progress

#1965 fix: 修复一级页面关闭弹窗出现多个
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
Labels: ready

#1968 Fix/plugin some qs
  app/renderer/src/main/src/pages/pluginHub/pluginUploadModal/PluginUploadModal.module.scss
  app/renderer/src/main/src/pages/pluginHub/pluginUploadModal/PluginUploadModal.tsx
  app/renderer/src/main/src/pages/plugins/log/PluginLog.tsx
Labels: ready

#1956 Song/feat/down body
  app/main/handlers/queryHTTPFlow.js
  app/protos/grpc.proto
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
  app/renderer/src/main/src/utils/editors.tsx
Labels: ready

#1955 feat: HTTP数据包变形接口替换
  app/renderer/src/main/src/components/yakitUI/YakitEditor/contextMenus.tsx
  app/renderer/src/main/src/pages/codec/NewCodec.tsx
Labels: ready

#1967 Yj/feat/yak runner check
  app/protos/grpc.proto
  app/renderer/src/main/package.json
  app/renderer/src/main/src/assets/icon/outline.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/StaticYakitEditor.scss
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditorType.ts
  app/renderer/src/main/src/components/yakitUI/YakitMenu/YakitMenu.tsx
  app/renderer/src/main/src/components/yakitUI/YakitMenu/yakitMenu.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitTextArea/YakitTextArea.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitTextArea/YakitTextArea.tsx
  app/renderer/src/main/src/pages/YakRunner/AuditCode/AuditCode.module.scss
  app/renderer/src/main/src/pages/YakRunner/AuditCode/AuditCode.tsx
  app/renderer/src/main/src/pages/YakRunner/AuditCode/AuditCodeType.d.ts
  app/renderer/src/main/src/pages/YakRunner/AuditCode/AuditTree/AuditMap.ts
  app/renderer/src/main/src/pages/YakRunner/AuditCode/AuditTree/ChildMap.ts
  app/renderer/src/main/src/pages/YakRunner/BottomEditorDetails/BottomEditorDetails.tsx
  app/renderer/src/main/src/pages/YakRunner/BottomEditorDetails/BottomEditorDetailsType.d.ts
  app/renderer/src/main/src/pages/YakRunner/BottomSideBar/BottomSideBar.tsx
  app/renderer/src/main/src/pages/YakRunner/CollapseList/CollapseList.tsx
  app/renderer/src/main/src/pages/YakRunner/CollapseList/CollapseListType.ts
  app/renderer/src/main/src/pages/YakRunner/FileTree/FileTree.tsx
  app/renderer/src/main/src/pages/YakRunner/FileTree/FileTreeType.d.ts
  app/renderer/src/main/src/pages/YakRunner/LeftSideBar/LeftSideBar.module.scss
  app/renderer/src/main/src/pages/YakRunner/LeftSideBar/LeftSideBar.tsx
  app/renderer/src/main/src/pages/YakRunner/LeftSideBar/LeftSideBarType.d.ts
  app/renderer/src/main/src/pages/YakRunner/RightAuditDetail/GraphInfoMap.ts
  app/renderer/src/main/src/pages/YakRunner/RightAuditDetail/RightAuditDetail.module.scss
  app/renderer/src/main/src/pages/YakRunner/RightAuditDetail/RightAuditDetail.tsx
  app/renderer/src/main/src/pages/YakRunner/RightSideBar/RightSideBar.module.scss
  app/renderer/src/main/src/pages/YakRunner/RightSideBar/RightSideBar.tsx
  app/renderer/src/main/src/pages/YakRunner/RightSideBar/RightSideBarType.d.ts
  app/renderer/src/main/src/pages/YakRunner/RunnerFileTree/RunnerFileTree.module.scss
  app/renderer/src/main/src/pages/YakRunner/RunnerFileTree/RunnerFileTree.tsx
  app/renderer/src/main/src/pages/YakRunner/RunnerTabs/RunnerTabs.module.scss
  app/renderer/src/main/src/pages/YakRunner/RunnerTabs/RunnerTabs.tsx
  app/renderer/src/main/src/pages/YakRunner/RunnerTabs/RunnerTabsType.d.ts
  app/renderer/src/main/src/pages/YakRunner/YakHelpDoc/YakHelpDoc.tsx
  app/renderer/src/main/src/pages/YakRunner/YakRunner.tsx
  app/renderer/src/main/src/pages/YakRunner/YakRunnerType.d.ts
  app/renderer/src/main/src/pages/YakRunner/hooks/YakRunnerContext.ts
  app/renderer/src/main/src/pages/YakRunner/icon.tsx
  app/renderer/src/main/src/pages/YakRunner/utils.ts
  app/renderer/src/main/src/pages/payloadGenerater/NewJavaPayloadPage.tsx
  app/renderer/src/main/src/pages/payloadManager/newPayload.tsx
  app/renderer/src/main/src/pages/plugins/baseComment.module.scss
  app/renderer/src/main/src/pages/plugins/baseComment.tsx
  app/renderer/src/main/src/pages/reverseServer/ReverseTable.tsx
  app/renderer/src/main/src/utils/eventBus/events/yakRunner.ts
  app/renderer/src/main/yarn.lock
Labels: ready

#1971 Song/feat/mitm chrome params
  app/main/handlers/chromelauncher.js
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.module.scss
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResizeType.d.ts
  app/renderer/src/main/src/defaultConstants/mitm.ts
  app/renderer/src/main/src/pages/mitm/MITMChromeLauncher.tsx
  app/renderer/src/main/src/pages/mitm/MITMPage.module.scss
  app/renderer/src/main/src/yakitGV.ts
Labels: ready

#1970 Luoluo/feature/web fuzzer drop number show
  app/protos/grpc.proto
  app/renderer/src/main/src/defaultConstants/HTTPFuzzerPage.ts
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequenceType.d.ts
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/store/fuzzerSequence.ts
Labels: ready

#1972 feat: 企业版游客信息统计埋点
  app/renderer/src/main/src/components/layout/UILayout.tsx
Labels: ready

#1973 fix: 修改错误命名
  .github/workflows/yakit-ce.yml
Labels: ready

#1974 Luoluo/feature/local plugin execute log
  app/renderer/src/main/src/pages/invoker/YakitLogFormatter.module.scss
  app/renderer/src/main/src/pages/invoker/YakitLogFormatter.tsx
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/LocalPluginLog.module.scss
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/LocalPluginLog.tsx
Labels: ready

#1969 Yj/fix optimize 08 28
  app/protos/grpc.proto
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.module.scss
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitForm.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitForm.tsx
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitFormType.d.ts
  app/renderer/src/main/src/pages/YakRunner/AuditCode/AuditCode.tsx
  app/renderer/src/main/src/pages/YakRunner/AuditCode/AuditCodeType.d.ts
  app/renderer/src/main/src/pages/YakRunner/RightAuditDetail/RightAuditDetail.tsx
  app/renderer/src/main/src/pages/YakRunner/RunnerFileTree/RunnerFileTree.tsx
  app/renderer/src/main/src/pages/YakRunner/YakRunner.tsx
  app/renderer/src/main/src/pages/YakRunner/keyDown/keyDown.ts
  app/renderer/src/main/src/pages/YakRunner/utils.ts
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/ResponseAllDataCard.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerEditorMenu.tsx
  app/renderer/src/main/src/pages/layout/HeardMenu/HeardMenu.module.scss
  app/renderer/src/main/src/pages/layout/HeardMenu/HeardMenu.tsx
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeard.tsx
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeardType.d.ts
  app/renderer/src/main/src/pages/plugins/pluginBatchExecutor/pluginBatchExecutor.tsx
  app/renderer/src/main/src/pages/securityTool/newBrute/NewBrute.tsx
  app/renderer/src/main/src/pages/securityTool/newPortScan/NewPortScan.tsx
  app/renderer/src/main/src/pages/securityTool/newPortScan/NewPortScanType.d.ts
  app/renderer/src/main/src/pages/simpleDetect/SimpleDetect.tsx
  app/renderer/src/main/src/pages/simpleDetect/SimpleDetectType.d.ts
  app/renderer/src/main/src/utils/eventBus/events/yakRunner.ts
  app/renderer/src/main/src/utils/notification.tsx
  app/renderer/src/main/src/utils/prettifyPacket.tsx
Labels: ready

#1976 fix: -
  app/protos/grpc.proto
Labels: ready

#1964 fix(yak-theme): backtick without escape
  app/renderer/src/main/src/utils/monacoSpec/yakEditor.ts
Labels: ready

#1980 fix: 文案还原
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
Labels: ready

#1981 feat: 菜单栏新增部分编码
  app/renderer/src/main/src/pages/layout/publicMenu/MenuCodec.module.scss
  app/renderer/src/main/src/pages/layout/publicMenu/MenuCodec.tsx
Labels: ready

#1985 luoluo/feature/lodash-types
  app/renderer/src/main/package.json
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/pages/YakRunner/RunnerTabs/RunnerTabs.tsx
  app/renderer/src/main/src/pages/cve/CVETable.tsx
  app/renderer/src/main/src/pages/fuzzer/components/HTTPFuzzerPageTable/HTTPFuzzerPageTable.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/pluginEditor/editorCode/EditorCode.tsx
  app/renderer/src/main/src/pages/pluginEditor/utils/convert.ts
  app/renderer/src/main/src/pages/pluginHub/defaultConstant.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListLocal.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListOnline.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/funcTemplate.tsx
  app/renderer/src/main/src/pages/plugins/funcTemplate.tsx
  app/renderer/src/main/src/pages/plugins/local/PluginsLocal.tsx
  app/renderer/src/main/src/pages/plugins/local/PluginsLocalDetail.tsx
  app/renderer/src/main/src/pages/plugins/manage/PluginManageDetail.tsx
  app/renderer/src/main/src/pages/plugins/online/PluginsOnlineDetail.tsx
  app/renderer/src/main/src/pages/plugins/pluginDebug/PluginDebug.tsx
  app/renderer/src/main/src/pages/plugins/utils.ts
  app/renderer/src/main/src/pages/reverseServer/ReverseTable.tsx
  app/renderer/src/main/src/pages/simpleDetect/SimpleDetect.tsx
  app/renderer/src/main/yarn.lock
Labels: ready

#1991 feat: mitm页面插件顺序调整
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/invoker/schema.ts
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginHijackContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginLocalList.tsx
Labels: ready

#1992 feat: 域名资产页面替换
  app/renderer/src/main/src/pages/assetViewer/DomainAssetPage.module.scss
  app/renderer/src/main/src/pages/assetViewer/DomainAssetPage.tsx
Labels: ready

#1993 feat: websocket新页面
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
  app/renderer/src/main/src/defaultConstants/WebsocketFuzzer.ts
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/websocket/HTTPFlowForWebsocketViewer.tsx
  app/renderer/src/main/src/pages/websocket/WebsocketClientOperator.tsx
  app/renderer/src/main/src/pages/websocket/WebsocketFlowViewer.tsx
  app/renderer/src/main/src/pages/websocket/WebsocketFuzzer.module.scss
  app/renderer/src/main/src/pages/websocket/WebsocketFuzzer.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/store/pageInfo.ts
Labels: ready

#1996 Yj/fix/yak runner/9 18
  app/renderer/src/main/src/pages/YakRunner/AuditCode/AuditCode.tsx
  app/renderer/src/main/src/pages/YakRunner/AuditCode/AuditCodeType.d.ts
  app/renderer/src/main/src/pages/YakRunner/BottomEditorDetails/BottomEditorDetails.tsx
  app/renderer/src/main/src/pages/YakRunner/RightAuditDetail/RightAuditDetail.tsx
  app/renderer/src/main/src/pages/YakRunner/RunnerTabs/RunnerTabs.tsx
  app/renderer/src/main/src/pages/YakRunner/YakRunner.tsx
  app/renderer/src/main/src/pages/home/Home.tsx
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeard.tsx
  app/renderer/src/main/src/pages/plugins/pluginsType.d.ts
Labels: ready

#1995 Luoluo/feature/new wf recover history
  app/main/handlers/httpFuzzer.js
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerHistory.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContentType.d.ts
  app/renderer/src/main/src/pages/layout/mainOperatorContent/TabRenameModalContent.module.scss
  app/renderer/src/main/src/pages/layout/mainOperatorContent/TabRenameModalContent.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/utils.ts
Labels: ready

#1997 feat: 自定义指纹扫描
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitForm.tsx
  app/renderer/src/main/src/pages/fuzzer/InsertFileFuzzTag.tsx
  app/renderer/src/main/src/pages/portscan/PortScanPage.tsx
  app/renderer/src/main/src/pages/securityTool/newPortScan/NewPortScan.tsx
  app/renderer/src/main/src/pages/securityTool/newPortScan/NewPortScanExtraParamsDrawer.tsx
Labels: ready

#2001 fix: 解除部分屏蔽项
  app/renderer/src/main/src/routes/deprecatedMenu.ts
Labels: ready

#2006 fix: 检测结果保留原有格式
  app/renderer/src/main/src/pages/pluginHub/hubExtraOperate/HubExtraOperate.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/funcTemplate.tsx
  app/renderer/src/main/src/pages/plugins/funcTemplate.tsx
  app/renderer/src/main/src/pages/plugins/log/PluginLogDetail.tsx
  app/renderer/src/main/src/pages/plugins/manage/PluginManageDetail.tsx
Labels: ready

#2007 fix: 配置私有域代理为空时也需要存缓存
  app/renderer/src/main/src/components/ConfigPrivateDomain/ConfigPrivateDomain.tsx
Labels: ready

#2008 feat: webFuzzer表格新增延迟返回筛选
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/components/HTTPFuzzerPageTable/HTTPFuzzerPageTable.tsx
Labels: ready

#2011 feat: 部分旧组件替换为新组件
  app/renderer/src/main/src/components/FuzzableParamList.tsx
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/HTTPFlowMiniTable.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/hTTPFlowDetail.module.scss
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/layout/GlobalState.tsx
  app/renderer/src/main/src/components/layout/PerformanceDisplay.tsx
  app/renderer/src/main/src/components/yakitUI/YakitPopconfirm/YakitPopconfirm.tsx
  app/renderer/src/main/src/components/yakitUI/YakitTabs/YakitTabs.tsx
  app/renderer/src/main/src/pages/LicensePage.tsx
  app/renderer/src/main/src/pages/Login.tsx
  app/renderer/src/main/src/pages/assetViewer/ReportViewerPage.tsx
  app/renderer/src/main/src/pages/chaosmaker/ChaosMakerRuleImport.tsx
  app/renderer/src/main/src/pages/chaosmaker/ChaosMakerRunningSteps.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/InsertFileFuzzTag.tsx
  app/renderer/src/main/src/pages/fuzzer/StringFuzzer.tsx
  app/renderer/src/main/src/pages/loginOperationMenu/AccountAdminPage.tsx
  app/renderer/src/main/src/pages/loginOperationMenu/LicenseAdminPage.tsx
  app/renderer/src/main/src/pages/loginOperationMenu/NewLicenseAdminPage.module.scss
  app/renderer/src/main/src/pages/loginOperationMenu/NewLicenseAdminPage.tsx
  app/renderer/src/main/src/pages/loginOperationMenu/RoleAdminPage.tsx
  app/renderer/src/main/src/pages/loginOperationMenu/TrustListPage.module.scss
  app/renderer/src/main/src/pages/loginOperationMenu/TrustListPage.scss
  app/renderer/src/main/src/pages/loginOperationMenu/TrustListPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMHTTPFlowMiniTableCard.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMFilters.tsx
  app/renderer/src/main/src/pages/payloadManager/newPayloadTable.tsx
  app/renderer/src/main/src/pages/risks/RiskTable.tsx
  app/renderer/src/main/src/pages/vulinbox/VulinboxManager.tsx
  app/renderer/src/main/src/pages/yakitStore/viewers/WebsiteTree.tsx
  app/renderer/src/main/src/pages/yakitStore/viewers/base.scss
  app/renderer/src/main/src/pages/yakitStore/viewers/base.tsx
  app/renderer/src/main/src/utils/ConfigPcapPermission.tsx
  app/renderer/src/main/src/utils/ConfigYaklangEnvironment.tsx
  app/renderer/src/main/src/utils/InvalidCacheAndUserData.tsx
  app/renderer/src/main/src/utils/basic.tsx
  app/renderer/src/main/src/utils/extractor.tsx
Labels: ready

#2013 Song/feat/simple detect new fun
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/portscan/PortScanPage.tsx
  app/renderer/src/main/src/pages/securityTool/newPortScan/NewPortScan.tsx
  app/renderer/src/main/src/pages/securityTool/newPortScan/NewPortScanExtraParamsDrawer.tsx
  app/renderer/src/main/src/pages/simpleDetect/SimpleDetect.tsx
Labels: ready

#2004 feat: 增加缓存项
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
Labels: Merge after publishing

#2012 Song/feat/ee system seting
  app/renderer/src/main/src/NewApp.tsx
  app/renderer/src/main/src/components/ConfigPrivateDomain/ConfigPrivateDomain.tsx
  app/renderer/src/main/src/components/layout/UILayout.tsx
  app/renderer/src/main/src/pages/EnterpriseJudgeLogin.tsx
  app/renderer/src/main/src/pages/MainOperator.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/services/swagger/resposeType.ts
  app/renderer/src/main/src/store/index.ts
Labels: ready

#2017 feat: 文案修改
  app/renderer/src/main/src/pages/yakitStore/viewers/base.tsx
Labels: ready
