Repository yaklang/yakit, pull requests merged in 2025-02, with the labels that each got.

#2329 feat: 并发负载rps、cps
  app/renderer/src/main/package.json
  app/renderer/src/main/src/components/layout/PerformanceDisplay.tsx
  app/renderer/src/main/src/components/layout/performanceDisplay.module.scss
  app/renderer/src/main/src/pages/fuzzer/FuzzerConcurrentLoad/FuzzerConcurrentLoad.tsx
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/ResponseCard.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/utils/duplex/duplex.tsx
  app/renderer/src/main/src/utils/eventBus/events/refreshData.ts
  app/renderer/src/main/yarn.lock
Labels: ready

#2325 clear redundancy const
  app/renderer/src/main/src/components/layout/HelpDoc/HelpDoc.tsx
Labels: ready

#2328 fix: 热加载缓存导致的发送fuzzer数据问题
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerHotPatch.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
Labels: ready

#2330 feat: 文案调整
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMHijackedContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMFilters.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMFiltersModal.tsx
Labels: ready

#2332 new multi-platform ci
  .github/workflows/multi-platform-build.yml
Labels: ready

#2334 update ci file description
  .github/workflows/multi-platform-build.yml
Labels: ready

#2337 fix: -
  app/renderer/src/main/src/pages/yakRunnerAuditHole/YakitAuditHoleTable/YakitAuditHoleTable.tsx
Labels: ready

#2321 Adjust software startup logic
  app/main/handlers/upgradeUtil.js
  app/main/handlers/utils/network.js
  app/main/handlers/utils/requestWithProgress.js
  app/main/uiOperate/yaklangAndYakit.js
  app/renderer/src/main/src/NewApp.tsx
  app/renderer/src/main/src/apiUtils/grpc.ts
  app/renderer/src/main/src/components/layout/CheckEngineVersion/CheckEngineVersion.module.scss
  app/renderer/src/main/src/components/layout/CheckEngineVersion/CheckEngineVersion.tsx
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/layout/GlobalState.tsx
  app/renderer/src/main/src/components/layout/HelpDoc/HelpDoc.tsx
  app/renderer/src/main/src/components/layout/LocalEngine/LocalEngine.tsx
  app/renderer/src/main/src/components/layout/LocalEngine/LocalEngineType.d.ts
  app/renderer/src/main/src/components/layout/UILayout.tsx
  app/renderer/src/main/src/components/layout/update/InstallEngine.tsx
  app/renderer/src/main/src/components/layout/update/UpdateYakitAndYaklang.module.scss
  app/renderer/src/main/src/components/layout/update/UpdateYakitAndYaklang.tsx
  app/renderer/src/main/src/constants/hardware.ts
  app/renderer/src/main/src/enums/engine.ts
  app/renderer/src/main/src/pages/pluginHub/hooks/useGetSetState.ts
  app/renderer/src/main/src/utils/eventBus/events/updateYakitYaklang.ts
Labels: ready

#2338 fix https over http connect qs
  app/main/handlers/utils/network.js
  app/main/httpServer.js
  app/main/uiOperate/networkJudgment.js
  app/renderer/src/main/src/services/fetch.ts
  package.json
  yarn.lock
Labels: ready

#2342 fix: -
  app/renderer/src/main/src/routes/publicIcon.tsx
Labels: ready

#2345 Song/fix/rule search
  app/protos/grpc.proto
  app/renderer/src/main/src/components/HTTPFlowExtractedDataTable.tsx
Labels: ready

#2347 Song/feat/history import export
  app/main/handlers/queryHTTPFlow.js
  app/protos/grpc.proto
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.module.scss
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/HTTPHistory.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.module.scss
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/layout/publicMenu/ExtraMenu.tsx
  app/renderer/src/main/src/store/pageInfo.ts
  app/renderer/src/main/src/utils/eventBus/events/history.ts
  app/renderer/src/main/src/utils/yakQueryHTTPFlow.tsx
Labels: ready

#2354 Song/feat/ee data statistics use detail
  app/renderer/src/main/src/components/layout/UILayout.tsx
  app/renderer/src/main/src/pages/dataStatistics/DataStatistics.module.scss
  app/renderer/src/main/src/pages/dataStatistics/DataStatistics.tsx
  app/renderer/src/main/src/services/swagger/resposeType.ts
  app/renderer/src/main/src/utils/visitorsStatistics.tsx
Labels: ready

#2361 feat: fuzzer单个发包编辑器编码存缓存
  app/renderer/src/main/src/enums/fuzzer.ts
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
Labels: ready

#2362 fix: fuzzer并发与加载图问题
  app/renderer/src/main/src/pages/fuzzer/FuzzerConcurrentLoad/FuzzerConcurrentLoad.tsx
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
Labels: ready

#2363 fix: 延时提交参数设置，修复jsonSchema拿不到最新值
  app/renderer/src/main/src/pages/mitm/MITMYakScriptLoader.tsx
Labels: ready

#2364 Song/feat/regexp groups
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/mitm/MITMRule/MITMRule.tsx
  app/renderer/src/main/src/pages/mitm/MITMRule/MITMRuleFromModal.tsx
  app/renderer/src/main/src/pages/mitm/MITMRule/MITMRuleType.ts
Labels: ready

#2365 Song/feat/history clear all shielding condition
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.module.scss
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMLog.tsx
  app/renderer/src/main/src/utils/eventBus/events/mitm.ts
Labels: ready

#2368 Chore/prod ci file
  .github/workflows/build-multi-prod.yml
  .github/workflows/gen-multi-render.yml
  .github/workflows/multi-platform-build.yml
  .github/workflows/publish-oss-version.yml
  .github/workflows/yakit-ci.yml.deprecate
  buildHooks/before_pack.js
  buildHooks/legacy_before_pack.js
  scripts/check-build-package.sh
  scripts/electron-build.sh
Labels: ready, need more test

#2369 feat: history&webFuzzer编辑器新增选中内容字节大小
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/editorUtils.ts
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/WebFuzzerNewEditor/WebFuzzerNewEditor.tsx
  app/renderer/src/main/src/pages/fuzzer/components/HTTPFuzzerPageTable/HTTPFuzzerPageTable.tsx
  app/renderer/src/main/src/pages/websocket/HTTPFlowForWebsocketViewer.tsx
Labels: ready

#2370 fix: 流量详情表格key值报错问题
  app/renderer/src/main/src/components/FuzzableParamList.tsx
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
Labels: ready

#2373 new ci file for se oss
  .github/workflows/publish-se-oss-yml
Labels: ready

#2374 Song/feat/webfuzzer table export custom fields
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/enums/fuzzer.ts
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPageExport.tsx
  app/renderer/src/main/src/utils/exporter.tsx
Labels: ready

#2378 update package version
  package.json
Labels: WIP: work in progress

#2379 modify download engine url
  .github/workflows/build-multi-prod.yml
  .github/workflows/multi-platform-build.yml
Labels: ready

#2382 Chore/modify ci code
  .github/workflows/breachtrace.yml.deprecated
  .github/workflows/gen-multi-render.yml
  .github/workflows/multi-platform-build.yml
  .github/workflows/publish-se-oss.yml
  .github/workflows/yakit-ce.yml.deprecated
  .github/workflows/yakit-ee.yml.deprecated
  .github/workflows/yakit-se.yml.deprecated
Labels: ready

#2386 Song/feat/payload refresh
  app/renderer/src/main/src/pages/payloadManager/newPayload.tsx
Labels: ready

#2388 Song/feat/resetmenu hint
  app/renderer/src/main/src/pages/layout/publicMenu/MenuPlugin.tsx
Labels: ready

#2391 feat: 反连状态调整
  app/renderer/src/main/src/components/layout/GlobalState.tsx
  app/renderer/src/main/src/pages/home/Home.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.module.scss
Labels: ready

#2393 add an option to disable unicode decode into right menu of webfuzzer
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditorType.ts
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
Labels: ready

#2397 ci file add option: cancel builtin version number
  .github/workflows/multi-platform-build.yml
Labels: ready

#2390 Yj/fix/2025 02 26
  app/renderer/src/main/src/components/JsonFormWrapper/editTable/EditTable.tsx
  app/renderer/src/main/src/pages/risks/VulnerabilityTypePie/VulnerabilityTypePie.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditHole/YakitAuditHoleTable/YakitAuditHoleTable.tsx
Labels: ready

#2398 fix bypass proxy for 127.0.0.1 traffic
  bins/scripts/google-chrome-plugin.zip
Labels: ready

#2400 update render-02-28
  .github/workflows/breachtrace.yml.deprecated
  .github/workflows/build-multi-prod.yml
  .github/workflows/gen-multi-render.yml
  .github/workflows/multi-platform-build.yml
  .github/workflows/publish-se-oss.yml
  .github/workflows/yakit-ce.yml.deprecated
  .github/workflows/yakit-ee.yml.deprecated
  .github/workflows/yakit-se.yml.deprecated
  app/renderer/src/main/src/components/JsonFormWrapper/editTable/EditTable.tsx
  app/renderer/src/main/src/components/configNetwork/ConfigNetworkPage.tsx
  app/renderer/src/main/src/components/layout/GlobalState.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditorType.ts
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
  app/renderer/src/main/src/pages/home/Home.tsx
  app/renderer/src/main/src/pages/layout/publicMenu/MenuPlugin.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMHijackedContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.module.scss
  app/renderer/src/main/src/pages/payloadManager/newPayload.tsx
  app/renderer/src/main/src/pages/risks/VulnerabilityTypePie/VulnerabilityTypePie.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditHole/YakitAuditHoleTable/YakitAuditHoleTable.tsx
  bins/scripts/google-chrome-plugin.zip
  package.json
Labels: ready
