Repository yaklang/yakit, pull requests merged in 2025-06, with the labels that each got.

#2600 v1.4.1-0530
  package.json
Labels: ready

#2604 Song/feat/rule management online
  app/main/handlers/syntaxFlow.js
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/ruleManagement/RuleManagement.module.scss
  app/renderer/src/main/src/pages/ruleManagement/RuleManagement.tsx
  app/renderer/src/main/src/pages/ruleManagement/RuleManagementType.d.ts
  app/renderer/src/main/src/pages/ruleManagement/api.ts
  app/renderer/src/main/src/pages/ruleManagement/template.tsx
  app/renderer/src/main/src/services/swagger/resposeType.ts
Labels: ready

#2587 feat(projectManager):support mysql database in irify
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/softwareSettings/ProjectManage.tsx
Labels: ready

#2612 fix: 文案替换
  app/renderer/src/main/src/pages/softwareSettings/ProjectManage.module.scss
  app/renderer/src/main/src/pages/softwareSettings/ProjectManage.tsx
Labels: ready

#2613 Luoluo/fix/init-menu-key
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
Labels: ready

#2605 Luoluo/feature/code-audit-add-filter-function-patch
  app/renderer/src/main/src/pages/yakRunnerAuditCode/GlobalFilterFunction/GlobalFilterFunction.tsx
Labels: ready

#2615 feat: 首页mitm跳转v2&菜单栏跳转v2
  app/renderer/src/main/src/defaultConstants/mitmV2.ts
  app/renderer/src/main/src/pages/fuzzer/components/ShareImport/index.tsx
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistoryAnalysis.tsx
  app/renderer/src/main/src/pages/home/Home.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/layout/publicMenu/MenuMode.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMServerStartForm.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/store/pageInfo.ts
Labels: ready

#2616 feat: 渲染端崩溃日志文件
  app/main/errorCollection.js
  app/main/index.js
  app/main/logFile.js
  app/main/preload.js
  app/renderer/src/main/src/NewApp.tsx
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/enums/localGlobal.ts
  app/renderer/src/main/src/pages/MainOperator.tsx
Labels: ready

#2617 Song/feat/rule update risk
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/ruleManagement/RuleManagement.module.scss
  app/renderer/src/main/src/pages/ruleManagement/RuleManagement.tsx
  app/renderer/src/main/src/pages/ruleManagement/RuleManagementType.d.ts
  app/renderer/src/main/src/pages/ruleManagement/template.tsx
Labels: ready

#2619 Song/fix/log output and try unlink yak
  app/main/handlers/upgradeUtil.js
  app/main/uiOperate/yaklangAndYakit.js
  app/renderer/src/main/src/components/layout/LocalEngine/LocalEngine.tsx
  app/renderer/src/main/src/components/layout/UILayout.tsx
  app/renderer/src/main/src/components/layout/update/InstallEngine.tsx
  app/renderer/src/main/src/components/layout/update/UpdateYakitAndYaklang.tsx
Labels: ready

#2620 Render Version To v1.06.06
  app/renderer/src/main/package.json
Labels: ready

#2621 v1.4.1-0606
  package.json
Labels: ready

#2626 feat: 接入md
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTable.tsx
Labels: ready

#2627 Yj/feat/irify shortcut
  app/renderer/src/main/src/NewApp.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
  app/renderer/src/main/src/components/configNetwork/ConfigNetworkPage.tsx
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/yakChat/chatCS.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditorType.ts
  app/renderer/src/main/src/pages/cve/CVETable.tsx
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistory/HTTPHistoryFilter.tsx
  app/renderer/src/main/src/pages/home/IRifyHome.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginLocalList.tsx
  app/renderer/src/main/src/pages/pluginEditor/addYakitPlugin/AddYakitPlugin.tsx
  app/renderer/src/main/src/pages/pluginEditor/modifyYakitPlugin/ModifyYakitPlugin.tsx
  app/renderer/src/main/src/pages/pluginEditor/pluginEditor/PluginEditor.tsx
  app/renderer/src/main/src/pages/pluginHub/group/PluginGroupList.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHub/PluginHub.tsx
  app/renderer/src/main/src/pages/shortcutKey/ShortcutKey.module.scss
  app/renderer/src/main/src/pages/shortcutKey/ShortcutKey.tsx
  app/renderer/src/main/src/pages/shortcutKey/type.d.ts
  app/renderer/src/main/src/pages/yakRunner/FileTree/FileTree.tsx
  app/renderer/src/main/src/pages/yakRunner/YakRunner.tsx
  app/renderer/src/main/src/pages/yakRunner/keyDown/keyDown.ts
  app/renderer/src/main/src/pages/yakRunnerAuditCode/AuditSearchModal/AuditSearch.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/BottomEditorDetails/BottomEditorDetails.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/BottomEditorDetails/RuleEditorBox/RuleEditorBox.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/RunnerTabs/RunnerTabs.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/YakRunnerAuditCode.tsx
  app/renderer/src/main/src/pages/yakitStore/viewers/base.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/utils/globalShortcutKey/events/global.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/multiple/yakitMultiple.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/page/chatCS.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/page/pluginHub.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/page/yakEditor.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/page/yakRunner.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/page/yakRunnerAuditCode.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/pageMaps.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/useShortcutKeyTrigger.ts
  app/renderer/src/main/src/utils/globalShortcutKey/shortcutKeyFocusHook/ShortcutKeyFocusHook.module.scss
  app/renderer/src/main/src/utils/globalShortcutKey/shortcutKeyFocusHook/ShortcutKeyFocusHook.tsx
  app/renderer/src/main/src/utils/globalShortcutKey/shortcutKeyFocusHook/hooks/ShortcutKeyFocusContext.ts
  app/renderer/src/main/src/utils/globalShortcutKey/shortcutKeyFocusHook/hooks/useDispatcher.ts
  app/renderer/src/main/src/utils/globalShortcutKey/shortcutKeyFocusHook/hooks/useStore.ts
  app/renderer/src/main/src/utils/globalShortcutKey/utils.ts
Labels: ready

#2629 Song/feat/packet hex
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/HTTPFlowExtractedDataTable.tsx
  app/renderer/src/main/src/components/OpenPacketNewWindow/OpenPacketNewWindow.tsx
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/WebFuzzerNewEditor/WebFuzzerNewEditor.tsx
  app/renderer/src/main/src/pages/fuzzer/components/HTTPFuzzerPageTable/HTTPFuzzerPageTable.tsx
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistoryAnalysis.tsx
  app/renderer/src/main/src/pages/misstatement/MisstatementDetail/MisstatementDetail.tsx
  app/renderer/src/main/src/pages/mitm/MITMManual/MITMManual.tsx
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTable.tsx
  app/renderer/src/main/src/utils/editors.module.scss
  app/renderer/src/main/src/utils/editors.tsx
Labels: ready

#2628 fix: mitmV1页面点击跳转直接跳转到v2页面不带参数
  app/renderer/src/main/src/pages/hacker/httpHacker.tsx
Labels: ready

#2622 feat：端口表新增刷新按钮
  app/renderer/src/main/src/pages/assetViewer/PortTable/PortTable.tsx
Labels: ready

#2635 Song/feat/fingerprint management
  app/main/handlers/fingerprint.js
  app/main/ipc.js
  app/protos/grpc.proto
  app/renderer/src/main/src/components/yakChat/ChatMarkdown.tsx
  app/renderer/src/main/src/components/yakChat/chatMarkdown.scss
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitForm.tsx
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitFormType.d.ts
  app/renderer/src/main/src/enums/yakitRoute.ts
  app/renderer/src/main/src/pages/fingerprintManage/FingerprintManage.module.scss
  app/renderer/src/main/src/pages/fingerprintManage/FingerprintManage.tsx
  app/renderer/src/main/src/pages/fingerprintManage/FingerprintRuleDom.tsx
  app/renderer/src/main/src/pages/fingerprintManage/ImportExportModal/ImportExportModal.module.scss
  app/renderer/src/main/src/pages/fingerprintManage/ImportExportModal/ImportExportModal.tsx
  app/renderer/src/main/src/pages/fingerprintManage/api.ts
  app/renderer/src/main/src/pages/layout/publicMenu/MenuMode.tsx
  app/renderer/src/main/src/pages/payloadManager/newPayloadTable.tsx
  app/renderer/src/main/src/pages/portscan/PortScanPage.tsx
  app/renderer/src/main/src/pages/ruleManagement/RuleManagement.tsx
  app/renderer/src/main/src/pages/ruleManagement/RuleManagementType.d.ts
  app/renderer/src/main/src/pages/ruleManagement/template.tsx
  app/renderer/src/main/src/pages/securityTool/newPortScan/NewPortScan.module.scss
  app/renderer/src/main/src/pages/securityTool/newPortScan/NewPortScan.tsx
  app/renderer/src/main/src/pages/securityTool/newPortScan/NewPortScanExtraParamsDrawer.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/routes/privateIcon.tsx
  app/renderer/src/main/src/routes/publicIcon.tsx
Labels: ready

#2636 Song/pref/history search
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
Labels: ready

#2532 AIAgent
  app/main/handleIPC.js
  app/main/handlers/mcpServere.js
  app/main/handlers/utils/network.js
  app/main/ipc.js
  app/main/uiOperate/yaklangAndYakit.js
  app/protos/grpc.proto
  app/renderer/src/main/package.json
  app/renderer/src/main/src/assets/aiAgent/yakit_run_quickly.gif
  app/renderer/src/main/src/assets/icon/colors.tsx
  app/renderer/src/main/src/assets/icon/outline.tsx
  app/renderer/src/main/src/assets/icon/solid.tsx
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/yakChat/ChatMarkdown.tsx
  app/renderer/src/main/src/components/yakitUI/YakitModal/YakitModal.tsx
  app/renderer/src/main/src/enums/aiAgent.ts
  app/renderer/src/main/src/enums/yakitRoute.ts
  app/renderer/src/main/src/pages/ai-agent/AIAgent.module.scss
  app/renderer/src/main/src/pages/ai-agent/AIAgent.tsx
  app/renderer/src/main/src/pages/ai-agent/AIAgentSideList.tsx
  app/renderer/src/main/src/pages/ai-agent/AIChatSetting.tsx
  app/renderer/src/main/src/pages/ai-agent/HistoryChat.tsx
  app/renderer/src/main/src/pages/ai-agent/MCPServer.tsx
  app/renderer/src/main/src/pages/ai-agent/ServerChat.tsx
  app/renderer/src/main/src/pages/ai-agent/ServerInfoModal.tsx
  app/renderer/src/main/src/pages/ai-agent/UtilModals.tsx
  app/renderer/src/main/src/pages/ai-agent/aiAgentType.d.ts
  app/renderer/src/main/src/pages/ai-agent/aiPlanReviewTree/AIPlanReviewTree.module.scss
  app/renderer/src/main/src/pages/ai-agent/aiPlanReviewTree/AIPlanReviewTree.tsx
  app/renderer/src/main/src/pages/ai-agent/aiPlanReviewTree/AIPlanReviewTreeType.d.ts
  app/renderer/src/main/src/pages/ai-agent/aiPlanReviewTree/icon.tsx
  app/renderer/src/main/src/pages/ai-agent/aiTree/AITree.module.scss
  app/renderer/src/main/src/pages/ai-agent/aiTree/AITree.tsx
  app/renderer/src/main/src/pages/ai-agent/aiTree/icon.tsx
  app/renderer/src/main/src/pages/ai-agent/aiTree/type.d.ts
  app/renderer/src/main/src/pages/ai-agent/chatTemplate/AIAgentChatTemplate.module.scss
  app/renderer/src/main/src/pages/ai-agent/chatTemplate/AIAgentChatTemplate.tsx
  app/renderer/src/main/src/pages/ai-agent/chatTemplate/AIEcharts.tsx
  app/renderer/src/main/src/pages/ai-agent/defaultConstant.tsx
  app/renderer/src/main/src/pages/ai-agent/grpc.ts
  app/renderer/src/main/src/pages/ai-agent/type/aiChat.d.ts
  app/renderer/src/main/src/pages/ai-agent/type/mcpClient.d.ts
  app/renderer/src/main/src/pages/ai-agent/useChatData.ts
  app/renderer/src/main/src/pages/ai-agent/useContext/AIAgentContext.ts
  app/renderer/src/main/src/pages/ai-agent/useContext/useDispatcher.ts
  app/renderer/src/main/src/pages/ai-agent/useContext/useStore.ts
  app/renderer/src/main/src/pages/ai-agent/useMCPData.ts
  app/renderer/src/main/src/pages/ai-agent/utils.ts
  app/renderer/src/main/src/pages/layout/publicMenu/MenuMode.tsx
  app/renderer/src/main/src/pages/plugins/builtInData.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/routes/privateIcon.tsx
  app/renderer/src/main/src/routes/publicIcon.tsx
  app/renderer/src/main/src/utils/eventBus/eventBus.ts
  app/renderer/src/main/src/utils/eventBus/events/aiAgent.ts
  app/renderer/src/main/src/utils/tool.ts
  app/renderer/src/main/yarn.lock
  package.json
  yarn.lock
Labels: ready

#2642 fix: 复原老版monaco中的快捷键
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
Labels: ready

#2643 Render Version To v1.06.16
  app/renderer/src/main/package.json
Labels: ready

#2652 Yj/fix/2025 06 19
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistory/HTTPHistoryFilter.tsx
  app/renderer/src/main/src/pages/mitm/MITMManual/MITMManual.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/AuditSearchModal/AuditSearch.tsx
Labels: ready

#2649 Song/feat/open console new win
  app/main/handlers/communication.js
  app/main/handlers/openConsoleNewWin/index.html
  app/main/handlers/openConsoleNewWin/index.js
  app/main/handlers/openConsoleNewWin/xterm-addon-fit@0.7.0/xterm-addon-fit.js
  app/main/handlers/openConsoleNewWin/xterm@5.3.0/xterm.css
  app/main/handlers/openConsoleNewWin/xterm@5.3.0/xterm.js
  app/main/ipc.js
  app/renderer/src/main/src/components/baseConsole/BaseConsole.tsx
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/layout/UILayout.tsx
  app/renderer/src/main/src/components/layout/hooks/useEngineConsole/useEngineConsole.ts
  app/renderer/src/main/src/components/layout/hooks/useMcp/useMcp.ts
  app/renderer/src/main/src/pages/MainOperator.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerHotPatch.module.scss
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerHotPatch.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginHijackContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.module.scss
  app/renderer/src/main/src/store/baseConsole.tsx
  app/renderer/src/main/src/utils/ConfigSystemMcp.tsx
  app/renderer/src/main/src/utils/eventBus/events/global.ts
  app/renderer/src/main/src/utils/openWebsite.tsx
  app/renderer/src/main/src/yakitGV.ts
Labels: ready

#2659 style:还原丢失的颜色变量
  app/renderer/src/main/src/theme/yakit.scss
Labels: ready

#2660 Render Version To v1.06.21
  app/renderer/src/main/package.json
Labels: Merge after publishing

#2661 v1.4.2-0620
  package.json
Labels: Merge after publishing

#2663 modify some text in tls config
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.tsx
Labels: ready

#2665 feat: webfuzzer历史记录保存加快捷键
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/utils/eventBus/events/webFuzzer.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/page/httpFuzzer.ts
  app/renderer/src/main/src/utils/globalShortcutKey/keyMaps.ts
  app/renderer/src/main/src/utils/globalShortcutKey/utils.ts
Labels: ready

#2671 feat(monaco):add header "X-Requested-With" suggestion
  app/renderer/src/main/src/pages/mitm/MITMContentReplacerHeaderOperator.tsx
  app/renderer/src/main/src/pages/mitm/MITMRule/MITMRuleFromModal.tsx
  app/renderer/src/main/src/utils/monacoSpec/fuzzHTTPMonacoSpec.ts
Labels: ready

#2658 style: 主题色
  app/main/handlers/openConsoleNewWin/index.html
  app/main/handlers/openConsoleNewWin/theme.css
  app/main/handlers/openNewChildWindow/index.css
  app/main/handlers/openNewChildWindow/index.html
  app/renderer/src/main/public/index.html
  app/renderer/src/main/public/initial-loading.css
Labels: ready

#2674 add hotpatch text
  app/renderer/src/main/src/defaultConstants/HTTPFuzzerPage.ts
Labels: ready

#2672 fix: 指纹下载目录不存在需要先创建
  app/main/handlers/fingerprint.js
Labels: ready

#2673 fix: 数据包高亮
  app/renderer/src/main/src/pages/plugins/operator/localPluginExecuteDetailHeard/LocalPluginExecuteDetailHeard.tsx
Labels: ready

#2675 Song/feat/rule list add search
  app/main/handlers/mitm.js
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistoryAnalysis.tsx
  app/renderer/src/main/src/pages/mitm/MITMRule/MITMRule.module.scss
  app/renderer/src/main/src/pages/mitm/MITMRule/MITMRule.tsx
Labels: ready

#2667 Luoluo/feature/ai tool
  app/main/handlers/mcpServere.js
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/ai-agent/AIAgent.module.scss
  app/renderer/src/main/src/pages/ai-agent/AIAgentSideList.tsx
  app/renderer/src/main/src/pages/ai-agent/aiAgentType.d.ts
  app/renderer/src/main/src/pages/ai-agent/aiToolList/AIToolList.module.scss
  app/renderer/src/main/src/pages/ai-agent/aiToolList/AIToolList.tsx
  app/renderer/src/main/src/pages/ai-agent/aiToolList/AIToolListType.d.ts
  app/renderer/src/main/src/pages/ai-agent/aiToolList/utils.ts
  app/renderer/src/main/src/pages/ai-agent/defaultConstant.tsx
Labels: ready

#2679 Song/feat/console more
  app/main/handlers/upgradeUtil.js
  app/main/uiOperate/yaklangAndYakit.js
  app/renderer/src/main/src/components/basics/YakitLoading.tsx
  app/renderer/src/main/src/components/layout/HelpDoc/HelpDoc.tsx
  app/renderer/src/main/src/components/layout/LocalEngine/LocalEngine.tsx
  app/renderer/src/main/src/components/layout/UILayout.tsx
  package.json
  yarn.lock
Labels: ready

#2678 Yj/feat/2025 06 11
  app/main/handlers/upgradeUtil.js
  app/main/handlers/utils/network.js
  app/protos/grpc.proto
  app/renderer/src/main/src/NewApp.tsx
  app/renderer/src/main/src/apiUtils/grpc.ts
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/layout/UILayout.tsx
  app/renderer/src/main/src/components/layout/update/DownloadYakit.tsx
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistory/HTTPHistoryFilter.tsx
  app/renderer/src/main/src/pages/mitm/MITMManual/MITMManual.tsx
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTable.module.scss
  app/renderer/src/main/src/pages/softwareSettings/ProjectManage.tsx
  app/renderer/src/main/src/utils/eventBus/events/global.ts
  app/renderer/src/main/src/utils/eventBus/events/updateYakitYaklang.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/global.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/pageMaps.ts
  app/renderer/src/main/src/utils/login.tsx
Labels: ready

#2682 v1.4.2-0627
  package.json
Labels: ready, Merge after publishing

#2680 Render Version To v1.06.27
  app/renderer/src/main/package.json
Labels: ready, Merge after publishing
