Repository yaklang/yakit, pull requests merged in 2025-07, with the labels that each got.

#2689 Song/feat/web fuzzer hot patch add
  app/main/handlers/httpFuzzer.js
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerHotPatch.tsx
Labels: ready

#2688 Yj/feat/mitm rule 06 30
  app/main/handlers/misc.js
  app/main/handlers/upgradeUtil.js
  app/main/handlers/utils/network.js
  app/renderer/src/main/src/NewApp.tsx
  app/renderer/src/main/src/components/layout/update/DownloadYaklang.tsx
  app/renderer/src/main/src/components/layout/update/UpdateYakitAndYaklang.tsx
  app/renderer/src/main/src/pages/mitm/MITMRule/MITMRule.tsx
Labels: ready

#2692 add GM cert download
  app/main/handlers/mitm.js
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMCertificateDownloadModal.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMFormAdvancedConfiguration.tsx
Labels: ready

#2694 fix: fuzzer序列bug以及性能优化&YakRunner部分语言支持
  app/renderer/src/main/config-overrides.js
  app/renderer/src/main/src/index.tsx
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequenceType.d.ts
  app/renderer/src/main/src/pages/yakRunner/utils.ts
Labels: ready

#2701 Render Version To v1.07.04
  app/renderer/src/main/package.json
Labels: Merge after publishing

#2700 v1.4.2-0704
  package.json
Labels: Merge after publishing

#2697 Song/feat/ssa result diff
  app/main/handlers/syntaxFlow.js
  app/protos/grpc.proto
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/enums/yakitRoute.ts
  app/renderer/src/main/src/pages/ssaResDiff/SsaResDiff.module.scss
  app/renderer/src/main/src/pages/ssaResDiff/SsaResDiff.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
Labels: ready

#2710 Yj/feat/irify 07 02
  app/main/handlers/auditRisk.js
  app/protos/grpc.proto
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/components/yakitUI/YakitModal/YakitModalConfirm.tsx
  app/renderer/src/main/src/pages/fuzzer/WebFuzzerPage/WebFuzzerPage.tsx
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistory/HTTPHistoryFilter.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMManual/MITMManual.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginLog/PluginLogOpt.tsx
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTable.module.scss
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTable.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditHole/YakitAuditHoleTable/YakitAuditHoleTable.module.scss
  app/renderer/src/main/src/pages/yakRunnerAuditHole/YakitAuditHoleTable/YakitAuditHoleTable.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditHole/YakitAuditHoleTable/YakitAuditHoleTableType.d.ts
  app/renderer/src/main/src/pages/yakRunnerAuditHole/YakitAuditHoleTable/utils.ts
  app/renderer/src/main/src/utils/eventBus/events/main.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/global.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/page/yakEditor.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/useShortcutKeyTrigger.ts
  app/renderer/src/main/src/utils/globalShortcutKey/shortcutKeyFocusHook/ShortcutKeyFocusHook.tsx
  app/renderer/src/main/src/utils/globalShortcutKey/shortcutKeyFocusHook/hooks/ShortcutKeyFocusContext.ts
  app/renderer/src/main/src/utils/globalShortcutKey/shortcutKeyFocusHook/hooks/useDispatcher.ts
  app/renderer/src/main/src/utils/globalShortcutKey/shortcutKeyFocusHook/hooks/useStore.ts
  app/renderer/src/main/src/utils/globalShortcutKey/utils.ts
Labels: ready

#2699 feat: 插件商店列表tab切换
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/HubListOnline.tsx
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/PluginHubList.module.scss
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/funcTemplate.tsx
  app/renderer/src/main/src/pages/plugins/baseTemplateType.ts
Labels: ready

#2717 fix: 修复 history 打开详情崩溃问题
  app/renderer/src/main/src/components/yakitUI/YakitDrawer/YakitDrawer.tsx
Labels: ready

#2727 Render Version To v1.07.11
  app/renderer/src/main/package.json
Labels: ready

#2736 feat: some feat
  app/renderer/src/main/src/pages/ai-agent/aiPlanReviewTree/AIPlanReviewTree.tsx
  app/renderer/src/main/src/pages/ai-agent/aiTree/AITree.tsx
  app/renderer/src/main/src/pages/ai-agent/aiTree/type.d.ts
  app/renderer/src/main/src/pages/ai-agent/aiTriageChat/AITriageChat.tsx
  app/renderer/src/main/src/pages/ai-agent/defaultConstant.tsx
  app/renderer/src/main/src/pages/ai-agent/type/aiChat.d.ts
  app/renderer/src/main/src/pages/ai-agent/useChatData.ts
Labels: ready

#2742 feat: add theme Hooks
  app/renderer/src/main/src/hook/useTheme/index.tsx
  app/renderer/src/main/src/index.tsx
  app/renderer/src/main/tsconfig.json
Labels: ready

#2729 add tab err boundary msg
  app/renderer/src/main/src/pages/ai-agent/chatTemplate/AIAgentChatTemplate.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
Labels: ready

#2741 pref: 兼容新增列以及删除列
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistory/HTTPHistoryFilter.tsx
Labels: ready

#2744 feat: 谷歌免配置启动按钮
  app/renderer/src/main/src/defaultConstants/mitm.ts
  app/renderer/src/main/src/enums/mitm.ts
  app/renderer/src/main/src/pages/mitm/MITMChromeLauncher.tsx
  app/renderer/src/main/src/pages/mitm/MITMPage.module.scss
  app/renderer/src/main/src/utils/ConfigSystemProxy.tsx
Labels: ready

#2743 Yj/feat/editor menu 07 14
  app/main/handlers/codec.js
  app/protos/grpc.proto
  app/renderer/src/main/src/assets/icon/outline.tsx
  app/renderer/src/main/src/components/layout/update/UpdateYakitAndYaklang.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
  app/renderer/src/main/src/pages/codec/NewCodec.module.scss
  app/renderer/src/main/src/pages/codec/NewCodec.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerEditorMenu.module.scss
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerEditorMenu.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/notepadManage/hook/useGoEditNotepad.ts
  app/renderer/src/main/src/pages/notepadManage/modifyNotepad/ModifyNotepadType.d.ts
  app/renderer/src/main/src/pages/notepadManage/modifyNotepad/modifyNotepadLocal/ModifyNotepadLocal.tsx
  app/renderer/src/main/src/pages/notepadManage/modifyNotepad/modifyNotepadLocal/ModifyNotepadLocalType.d.ts
  app/renderer/src/main/src/pages/notepadManage/modifyNotepad/modifyNotepadOnline/ModifyNotepadOnline.tsx
  app/renderer/src/main/src/store/pageInfo.ts
  app/renderer/src/main/src/utils/eventBus/events/main.ts
Labels: ready

#2747 Update/render 1.07.18
  app/renderer/src/main/package.json
  package.json
Labels: Merge after publishing

#2750 fix: 最小化免配置启动
  app/renderer/src/main/src/defaultConstants/mitm.ts
  app/renderer/src/main/src/pages/mitm/MITMChromeLauncher.tsx
Labels: ready

#2752 feat: 去掉chartCs
  app/renderer/src/main/src/components/yakChat/chatCS.tsx
  app/renderer/src/main/src/pages/MainOperator.tsx
Labels: ready

#2755 feat: webFuzzer新增提示
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/components/HTTPFuzzerPageTable/HTTPFuzzerPageTable.tsx
Labels: ready

#2751 Luoluo/feature/ai risk and http flow and card
  app/renderer/src/main/src/components/yakitSideTab/YakitSideTab.module.scss
  app/renderer/src/main/src/components/yakitSideTab/YakitSideTab.tsx
  app/renderer/src/main/src/components/yakitSideTab/YakitSideTabType.d.ts
  app/renderer/src/main/src/components/yakitUI/YakitCollapse/YakitCollapse.module.scss
  app/renderer/src/main/src/hook/useHoldGRPCStream/useHoldGRPCStream.ts
  app/renderer/src/main/src/pages/ai-agent/AIChatSetting/AIChatSetting.module.scss
  app/renderer/src/main/src/pages/ai-agent/aiAgentType.d.ts
  app/renderer/src/main/src/pages/ai-agent/aiTaskChat/AITaskChat.module.scss
  app/renderer/src/main/src/pages/ai-agent/aiTaskChat/AITaskChat.tsx
  app/renderer/src/main/src/pages/ai-agent/chatTemplate/AIAgentChatTemplate.module.scss
  app/renderer/src/main/src/pages/ai-agent/chatTemplate/AIAgentChatTemplate.tsx
  app/renderer/src/main/src/pages/ai-agent/chatTemplate/AIChatTool.module.scss
  app/renderer/src/main/src/pages/ai-agent/chatTemplate/AIChatTool.tsx
  app/renderer/src/main/src/pages/ai-agent/defaultConstant.tsx
  app/renderer/src/main/src/pages/ai-agent/type/aiChat.d.ts
  app/renderer/src/main/src/pages/ai-agent/useChatData.ts
  app/renderer/src/main/src/pages/plugins/operator/horizontalScrollCard/HorizontalScrollCard.module.scss
  app/renderer/src/main/src/pages/plugins/operator/horizontalScrollCard/HorizontalScrollCard.tsx
  app/renderer/src/main/src/pages/plugins/operator/horizontalScrollCard/HorizontalScrollCardType.d.ts
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/PluginExecuteResult.module.scss
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/PluginExecuteResult.tsx
  app/renderer/src/main/src/pages/risks/YakitRiskTable/utils.ts
Labels: WIP: work in progress

#2759 feat: 捕获找不到谷歌插件的报错
  app/renderer/src/main/src/NewApp.tsx
Labels: ready

#2758 Yj/fix/07 21
  app/protos/grpc.proto
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTableForm.tsx
  app/renderer/src/main/src/components/configNetwork/NewThirdPartyApplicationConfig.tsx
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/enums/history.ts
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistory/HTTPHistoryFilter.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMLog.tsx
  app/renderer/src/main/src/pages/payloadManager/newPayloadTable.module.scss
  app/renderer/src/main/src/pages/payloadManager/newPayloadTable.tsx
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTable.tsx
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTableType.d.ts
  app/renderer/src/main/src/pages/yakJavaDecompiler/utils.ts
  app/renderer/src/main/src/pages/yakRunner/RunnerTabs/RunnerTabs.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/utils/yakQueryHTTPFlow.tsx
Labels: ready

#2764 Song/fix/http detail refresh
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
Labels: ready

#2766 pref: 获取hash引擎错误日志
  app/main/handlers/utils/network.js
  app/renderer/src/main/src/components/layout/GlobalState.tsx
Labels: ready

#2769 Yj/feat/irify 07 28
  app/main/menu.js
  app/renderer/src/main/src/components/yakitUI/YakitEditor/EditorMenu.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditorType.ts
  app/renderer/src/main/src/components/yakitUI/YakitEditor/contextMenus.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
  app/renderer/src/main/src/pages/mitm/MITMManual/MITMManual.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMManual.tsx
  app/renderer/src/main/src/pages/plugins/funcTemplate.tsx
  app/renderer/src/main/src/pages/plugins/funcTemplateType.ts
  app/renderer/src/main/src/pages/ruleManagement/template.tsx
  app/renderer/src/main/src/pages/shortcutKey/ShortcutKey.tsx
  app/renderer/src/main/src/pages/websocket/HTTPFlowForWebsocketViewer.tsx
  app/renderer/src/main/src/pages/yakJavaDecompiler/FileTree/FileTree.tsx
  app/renderer/src/main/src/pages/yakJavaDecompiler/FileTree/icon.ts
  app/renderer/src/main/src/pages/yakJavaDecompiler/RunnerTabs/RunnerTabs.tsx
  app/renderer/src/main/src/pages/yakJavaDecompiler/YakJavaDecompiler.tsx
  app/renderer/src/main/src/pages/yakJavaDecompiler/utils.ts
  app/renderer/src/main/src/pages/yakRunnerAuditCode/AuditCode/AuditCode.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/FileTree/FileTree.module.scss
  app/renderer/src/main/src/pages/yakRunnerAuditCode/FileTree/FileTree.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/FileTree/icon.ts
  app/renderer/src/main/src/pages/yakRunnerAuditCode/RunnerFileTree/RunnerFileTree.module.scss
  app/renderer/src/main/src/pages/yakRunnerAuditCode/RunnerFileTree/RunnerFileTree.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/RunnerFileTree/RunnerFileTreeType.d.ts
  app/renderer/src/main/src/pages/yakRunnerAuditCode/RunnerTabs/RunnerTabs.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/utils.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/global.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/page/yakEditor.ts
  app/renderer/src/main/src/utils/globalShortcutKey/events/pageMaps.ts
Labels: ready
