Repository yaklang/yakit, pull requests merged in 2025-09, with the labels that each got.

#2854 v1.4.4-0830
  package.json
Labels: ready

#2867 Yj/feat/irify 09 01
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/PluginExecuteResult.tsx
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTable.tsx
Labels: ready

#2872 Yj/feat/some 08 12
  app/main/handlers/syntaxFlow.js
  app/renderer/src/main/src/pages/assetViewer/ReportViewerPage.module.scss
  app/renderer/src/main/src/pages/assetViewer/ReportViewerPage.tsx
  app/renderer/src/main/src/pages/assetViewer/reportRenders/EchartsInit.tsx
  app/renderer/src/main/src/pages/assetViewer/reportRenders/markdownRender.module.scss
  app/renderer/src/main/src/pages/home/IRifyHome.module.scss
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/yakJavaDecompiler/RunnerTabs/RunnerTabs.module.scss
  app/renderer/src/main/src/pages/yakRunnerScanHistory/YakRunnerScanHistory.tsx
  app/renderer/src/main/src/utils/eventBus/eventBus.ts
  app/renderer/src/main/src/utils/eventBus/events/reportPage.ts
  report/template.zip
Labels: ready

#2870 update entity repositiy
  app/protos/grpc.proto
  app/renderer/src/main/src/components/playground/entityRepository/EntityRepositoryPage.tsx
Labels: ready

#2868 luoluo/feature/new-plugin-log-file
  app/main/utils/nodeFiles.js
  app/renderer/src/main/src/components/MilkdownEditor/CustomFile/CustomFile.tsx
  app/renderer/src/main/src/components/MilkdownEditor/CustomFile/utils.ts
  app/renderer/src/main/src/pages/ai-agent/AIAgent.tsx
  app/renderer/src/main/src/pages/invoker/YakitLogFormatter.module.scss
  app/renderer/src/main/src/pages/invoker/YakitLogFormatter.tsx
  app/renderer/src/main/src/pages/invoker/utils.ts
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/LocalPluginLog.module.scss
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/LocalPluginLog.tsx
  app/renderer/src/main/src/pages/plugins/operator/pluginExecuteResult/PluginExecuteResultType.d.ts
Labels: ready

#2863 fix: webfuzzer 错误埋点问题修复
  app/renderer/src/main/src/components/configNetwork/ConfigNetworkPage.tsx
  app/renderer/src/main/src/components/yakitUI/YakitModal/YakitModalConfirm.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/utils/showModal.tsx
Labels: ready

#2841 feat(theme): 优化主题与组件样式
  app/main/handlers/openNewChildWindow/index.js
  app/renderer/src/main/src/ChildNewApp.tsx
  app/renderer/src/main/src/components/BaseTitleBar/index.module.scss
  app/renderer/src/main/src/components/BaseTitleBar/index.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.module.scss
  app/renderer/src/main/src/components/TableVirtualResize/styleFunction.scss
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/components/layout/update/DownloadYakit.module.scss
  app/renderer/src/main/src/components/layout/update/DownloadYaklang.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitAutoComplete/YakitAutoComplete.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitButton/yakitButton.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitCollapse/YakitCollapse.module.scss
  app/renderer/src/main/src/components/yakitUI/YakitEditor/StaticYakitEditor.scss
  app/renderer/src/main/src/components/yakitUI/YakitResizeBox/YakitResizeBox.module.scss
  app/renderer/src/main/src/hook/useTheme/index.tsx
  app/renderer/src/main/src/index.tsx
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.module.scss
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.module.scss
  app/renderer/src/main/src/pages/fuzzer/MatcherAndExtractionCard/MatcherAndExtraction.module.scss
  app/renderer/src/main/src/pages/fuzzer/StringFuzzer.tsx
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistory/HTTPHistoryFilter.module.scss
  app/renderer/src/main/src/pages/layout/mainOperatorContent/BatchAddNewGroup.tsx
  app/renderer/src/main/src/pages/layout/publicMenu/ExtraMenu.module.scss
  app/renderer/src/main/src/pages/layout/publicMenu/ExtraMenu.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.module.scss
  app/renderer/src/main/src/pages/payloadManager/NewPayload.module.scss
  app/renderer/src/main/src/pages/pluginHub/pluginHubList/PluginHubList.module.scss
  app/renderer/src/main/src/pages/plugins/funcTemplate.module.scss
  app/renderer/src/main/src/pages/softwareSettings/ProjectManage.module.scss
  app/renderer/src/main/src/theme/componentsTheme/form.scss
  app/renderer/src/main/src/theme/componentsTheme/modal.scss
  app/renderer/src/main/src/utils/editors.module.scss
Labels: need more test

#2875 v1.4.4-0905
  package.json
Labels: Merge after publishing

#2884 fix(webfuzzer seq): fix issue where an error occurs when ResponseRaw …
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
Labels: ready

#2880 fix
  app/renderer/src/main/src/components/yakitUI/YakitEditor/StaticYakitEditor.scss
  app/renderer/src/main/src/utils/editors.tsx
  app/renderer/src/main/src/utils/monacoSpec/fuzzHTTPMonacoSpec.ts
  app/renderer/src/main/src/utils/monacoSpec/yakCompletionSchema.ts
Labels: ready

#2905 feat: aiAgent下载弹窗控制当前页面
  app/renderer/src/main/src/pages/ai-agent/aiModelList/AIModelList.tsx
  app/renderer/src/main/src/pages/ai-agent/aiModelList/installLlamaServerModelPrompt/InstallLlamaServerModelPrompt.module.scss
  app/renderer/src/main/src/pages/ai-agent/aiModelList/installLlamaServerModelPrompt/InstallLlamaServerModelPrompt.tsx
  app/renderer/src/main/src/pages/ai-agent/aiModelList/installLlamaServerModelPrompt/InstallLlamaServerModelPromptType.d.ts
Labels: ready

#2913 Yj/feat/irify report 09 15
  app/renderer/src/main/src/pages/portscan/CreateReport.tsx
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTable.tsx
  app/renderer/src/main/src/pages/securityTool/newPortScan/utils.ts
  app/renderer/src/main/src/pages/yakRunnerCodeScan/YakRunnerCodeScan.module.scss
  app/renderer/src/main/src/pages/yakRunnerCodeScan/YakRunnerCodeScan.tsx
  app/renderer/src/main/src/pages/yakRunnerCodeScan/YakRunnerCodeScanType.d.ts
  app/renderer/src/main/src/pages/yakRunnerScanHistory/YakRunnerScanHistory.tsx
Labels: ready

#2916 Song/feat/history translate
  app/renderer/src/main/public/locales/en/components.json
  app/renderer/src/main/public/locales/en/history.json
  app/renderer/src/main/public/locales/en/webFuzzer.json
  app/renderer/src/main/public/locales/en/yakitUi.json
  app/renderer/src/main/public/locales/zh/components.json
  app/renderer/src/main/public/locales/zh/history.json
  app/renderer/src/main/public/locales/zh/webFuzzer.json
  app/renderer/src/main/public/locales/zh/yakitUi.json
  app/renderer/src/main/src/components/DataExport/DataExport.tsx
  app/renderer/src/main/src/components/FuzzableParamList.tsx
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/HTTPFlowExtractedDataTable.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.module.scss
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTableForm.tsx
  app/renderer/src/main/src/components/HTTPHistory.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
  app/renderer/src/main/src/components/WebTree/WebTree.tsx
  app/renderer/src/main/src/components/yakitUI/YakitDatePicker/YakitDatePicker.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/StaticYakitEditor.scss
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/contextMenus.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/extraYakitEditor.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEmpty/YakitEmpty.tsx
  app/renderer/src/main/src/components/yakitUI/YakitForm/YakitForm.tsx
  app/renderer/src/main/src/i18n/i18n.ts
  app/renderer/src/main/src/i18n/useI18nNamespaces.ts
  app/renderer/src/main/src/pages/compare/DataCompare.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerEditorMenu.module.scss
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerEditorMenu.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistory/HTTPHistoryFilter.tsx
  app/renderer/src/main/src/pages/mitm/MITMHTTPFlowMiniTableCard.tsx
  app/renderer/src/main/src/pages/mitm/MITMManual/MITMManual.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMLog.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMManual.tsx
  app/renderer/src/main/src/pages/packetScanner/DefaultPacketScanGroup.tsx
  app/renderer/src/main/src/pages/packetScanner/PacketScanner.tsx
  app/renderer/src/main/src/pages/websocket/HTTPFlowForWebsocketViewer.tsx
  app/renderer/src/main/src/pages/websocket/WebsocketFrameHistory.tsx
  app/renderer/src/main/src/utils/clipboard.ts
  app/renderer/src/main/src/utils/editors.tsx
Labels: ready

#2915 feat: 文案&作用域
  app/renderer/src/main/public/locales/zh/yakitRoute.json
  app/renderer/src/main/src/components/layout/GlobalState.tsx
Labels: ready

#2911 feat: 引擎可用端口获取失败，日志文案修改
  app/renderer/src/main/src/components/layout/LocalEngine/LocalEngine.tsx
Labels: ready

#2908 feat: mitm热加载模板保存逻辑调整
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerHotPatch.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginHijackContent.tsx
Labels: ready

#2919 fix: 解决切换文件时高亮丢失
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
Labels: ready

#2920 pref: webfuzzer跳转流量分析器关闭网站树&打开规则热加载
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistory/HTTPHistoryFilter.tsx
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistoryAnalysis.tsx
Labels: ready

#2930 feat: 文案替换
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/defaultConstants/HTTPFuzzerPage.ts
  app/renderer/src/main/src/pages/payloadManager/newPayload.tsx
Labels: ready

#2922 fix: 分片错误信息抛出
  app/main/api/upload.js
  app/main/api/uploadOSS.js
  app/main/handlers/userInfo.js
  app/main/httpServer.js
Labels: ready

#2921 Feature/logger
  app/main/handlers/logger.js
  app/main/index.js
  app/main/ipc.js
  app/renderer/src/main/src/hook/useLogger/useLogger.ts
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
Labels: ready

#2942 fix: login
  app/main/httpServer.js
Labels: ready

#2946 fix: 知识库表格头部标题文案修改
  app/renderer/src/main/src/pages/KnowledgeBase/compoments/KnowledgeBaseModal.tsx
  app/renderer/src/main/src/pages/KnowledgeBase/knowledgeBaseTable.tsx
Labels: ready

#2948 fix: 安全渲染 HTML，保留样式，禁止 JS 执行
  app/renderer/src/main/public/locales/en/history.json
  app/renderer/src/main/public/locales/zh/history.json
  app/renderer/src/main/src/pages/mitm/MITMManual/MITMManual.tsx
  app/renderer/src/main/src/utils/editors.tsx
  app/renderer/src/main/src/utils/prettifyPacket.tsx
Labels: ready

#2949 v1.4.4-0928
  package.json
Labels: Merge after publishing
