Repository yaklang/yakit, pull requests merged in 2025-04, with the labels that each got.

#2476 Refactor/adjust start engine
  app/main/handlers/engineStatus.js
  app/main/ipc.js
  app/main/uiOperate/yaklangAndYakit.js
  app/protos/grpc.proto
  app/renderer/src/main/src/NewApp.tsx
  app/renderer/src/main/src/apiUtils/grpc.ts
  app/renderer/src/main/src/components/basics/YakitLoading.tsx
  app/renderer/src/main/src/components/layout/LocalEngine/LocalEngine.tsx
  app/renderer/src/main/src/components/layout/UILayout.tsx
  app/renderer/src/main/src/components/layout/YaklangEngineWatchDog.tsx
  app/renderer/src/main/src/components/layout/update/UpdateYakitAndYaklang.module.scss
  app/renderer/src/main/src/components/layout/update/UpdateYakitAndYaklang.tsx
  app/renderer/src/main/src/enums/localGlobal.ts
  app/renderer/src/main/src/utils/envfile.tsx
  app/renderer/src/main/src/utils/localCache/engine.ts
Labels: ready

#2474 Song/fix/data statistic token
  app/renderer/src/main/src/components/layout/UILayout.tsx
Labels: ready

#2472 fix:mitm & rule manage
  app/renderer/src/main/src/pages/mitm/MITMPage.module.scss
  app/renderer/src/main/src/pages/mitm/MITMYakScriptLoader.module.scss
  app/renderer/src/main/src/pages/mitm/MITMYakScriptLoader.tsx
  app/renderer/src/main/src/pages/ruleManagement/template.tsx
Labels: ready

#2478 fix: 校验引擎未知原因出现提示问题
  app/renderer/src/main/src/components/layout/GlobalState.tsx
  app/renderer/src/main/src/components/layout/LocalEngine/LocalEngine.tsx
Labels: ready

#2481 Song/style/web fuzzer hot code
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerHotPatch.module.scss
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerHotPatch.tsx
Labels: ready

#2480 Song/style/ai modal name
  app/renderer/src/main/src/components/configNetwork/NewThirdPartyApplicationConfig.tsx
Labels: ready

#2479 Song/feat/web fuzzer http set
  app/protos/grpc.proto
  app/renderer/src/main/src/defaultConstants/HTTPFuzzerPage.ts
  app/renderer/src/main/src/pages/MainOperator.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfig.tsx
  app/renderer/src/main/src/pages/fuzzer/HttpQueryAdvancedConfig/HttpQueryAdvancedConfigType.d.ts
  app/renderer/src/main/src/pages/fuzzer/components/ShareImportExportData/index.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
Labels: ready

#2477 Yj/feat/irify v2
  app/renderer/src/main/src/components/RollingLoadList/RollingLoadList.tsx
  app/renderer/src/main/src/components/yakCodemirror/YakCodemirror.moduleType.ts
  app/renderer/src/main/src/components/yakCodemirror/YakCodemirror.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditor.tsx
  app/renderer/src/main/src/components/yakitUI/YakitEditor/YakitEditorType.ts
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTable.tsx
  app/renderer/src/main/src/pages/ruleManagement/RuleManagement.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/AuditCode/AuditCode.module.scss
  app/renderer/src/main/src/pages/yakRunnerAuditCode/AuditCode/AuditCode.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/AuditCode/AuditCodeType.d.ts
  app/renderer/src/main/src/pages/yakRunnerAuditCode/AuditSearchModal/AuditSearch.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/BottomEditorDetails/BottomEditorDetails.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/BottomEditorDetails/RuleEditorBox/RuleEditorBox.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/RunnerFileTree/RunnerFileTree.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/RunnerTabs/RunnerTabs.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/YakRunnerAuditCode.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditHole/DocumentCollect/DocumentCollect.tsx
  app/renderer/src/main/src/pages/yakRunnerCodeScan/YakRunnerCodeScan.module.scss
  app/renderer/src/main/src/pages/yakRunnerCodeScan/YakRunnerCodeScan.tsx
  app/renderer/src/main/src/pages/yakRunnerCodeScan/YakRunnerCodeScanType.d.ts
  app/renderer/src/main/src/utils/eventBus/events/yakRunnerAudit.ts
  app/renderer/src/main/src/yakitGV.ts
Labels: ready

#2482 Render Version To v1.04.03
  app/renderer/src/main/package.json
Labels: Merge after publishing

#2483 v1.4.1-0403
  package.json
Labels: Merge after publishing

#2490 fix: 固定页面icon传递方式改变
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContentType.d.ts
Labels: ready

#2491 feat: mitm流量表total&selected
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/HTTPHistory.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMHijackedContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMLog.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.module.scss
Labels: ready

#2493 feat: codec历史记录新增复制
  app/renderer/src/main/src/pages/codec/NewCodec.module.scss
  app/renderer/src/main/src/pages/codec/NewCodec.tsx
Labels: ready

#2494 Song/fix/ai modal name
  app/renderer/src/main/src/components/configNetwork/NewThirdPartyApplicationConfig.tsx
Labels: ready

#2486 fix: link-engine-qs
  app/main/handlers/engineStatus.js
  app/main/handlers/upgradeUtil.js
  app/main/index.js
  app/main/ipc.js
  app/main/logFile.js
  app/main/uiOperate/yaklangAndYakit.js
  app/renderer/src/main/src/NewApp.tsx
  app/renderer/src/main/src/components/basics/YakitLoading.tsx
  app/renderer/src/main/src/components/basics/yakitLoading.module.scss
  app/renderer/src/main/src/components/layout/LocalEngine/LocalEngine.tsx
  app/renderer/src/main/src/components/layout/LocalEngine/LocalEngineType.d.ts
  app/renderer/src/main/src/components/layout/UILayout.tsx
  app/renderer/src/main/src/yakitGVDefine.d.ts
Labels: ready

#2489 Song/feat/risk table time filter
  app/protos/grpc.proto
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTable.tsx
  app/renderer/src/main/src/pages/risks/YakitRiskTable/YakitRiskTableType.d.ts
Labels: ready

#2500 Song/fix/tab limit
  app/renderer/src/main/src/pages/layout/mainOperatorContent/TabRenameModalContent.tsx
Labels: ready

#2499 Yj/fix/irify v2
  .github/workflows/build-multi-irify-prod.yml
  app/renderer/src/main/src/components/layout/GlobalState.tsx
  app/renderer/src/main/src/hook/useHoldGRPCStream/useHoldGRPCStream.ts
  app/renderer/src/main/src/hook/useVirtualTableHook/useVirtualTableHook.ts
  app/renderer/src/main/src/pages/yakRunnerAuditCode/AuditSearchModal/AuditSearch.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/RunnerTabs/RunnerTabs.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditCode/YakRunnerAuditCode.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditHole/YakitAuditHoleTable/YakitAuditHoleTable.tsx
  app/renderer/src/main/src/pages/yakRunnerAuditHole/YakitAuditHoleTable/YakitAuditHoleTableType.d.ts
  app/renderer/src/main/src/utils/notification.tsx
Labels: ready

#2502 Render Version To v1.04.11
  app/renderer/src/main/package.json
Labels: ready

#2503 v1.4.1-0411
  package.json
Labels: ready

#2511 feat: 上传数据还原
  app/main/api/upload.js
  app/renderer/src/main/src/components/layout/FuncDomain.tsx
  app/renderer/src/main/src/pages/SelectUpload.tsx
Labels: ready

#2473 Luoluo/feature/new-mitm-manual
  app/main/handlers/communication.js
  app/main/handlers/mitm.js
  app/main/handlers/mitmV2.js
  app/main/ipc.js
  app/protos/grpc.proto
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/HTTPHistory.tsx
  app/renderer/src/main/src/components/yakitSideTab/YakitSideTab.tsx
  app/renderer/src/main/src/components/yakitSideTab/YakitSideTabType.d.ts
  app/renderer/src/main/src/defaultConstants/mitmV2.ts
  app/renderer/src/main/src/enums/yakitRoute.ts
  app/renderer/src/main/src/pages/hacker/httpHacker.tsx
  app/renderer/src/main/src/pages/home/Home.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/mitm/Context/MITMContext.ts
  app/renderer/src/main/src/pages/mitm/MITMHTTPFlowMiniTableCard.tsx
  app/renderer/src/main/src/pages/mitm/MITMHacker/MITMHacker.module.scss
  app/renderer/src/main/src/pages/mitm/MITMHacker/MITMHacker.tsx
  app/renderer/src/main/src/pages/mitm/MITMHacker/MITMHackerType.d.ts
  app/renderer/src/main/src/pages/mitm/MITMHacker/utils.ts
  app/renderer/src/main/src/pages/mitm/MITMManual/MITMManual.module.scss
  app/renderer/src/main/src/pages/mitm/MITMManual/MITMManual.tsx
  app/renderer/src/main/src/pages/mitm/MITMManual/MITMManualType.d.ts
  app/renderer/src/main/src/pages/mitm/MITMManual/utils.ts
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMRule/MITMRule.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMHijackedContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMLog.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMManual.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMPluginHijackContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.module.scss
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMFiltersModal.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMServerStartForm.tsx
  app/renderer/src/main/src/pages/mitm/MITMYakScriptLoader.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/store/pageInfo.ts
  app/renderer/src/main/src/utils/editors.tsx
  app/renderer/src/main/src/utils/eventBus/events/mitm.ts
  app/renderer/src/main/src/yakitGV.ts
Labels: WIP: work in progress

#2515 Yj/fix/new mitm UI
  app/renderer/src/main/src/components/HTTPHistory.tsx
  app/renderer/src/main/src/components/playground/PacketListDemo.tsx
  app/renderer/src/main/src/components/yakitUI/YakitResizeBox/YakitResizeBox.tsx
  app/renderer/src/main/src/pages/home/Home.tsx
  app/renderer/src/main/src/pages/mitm/MITMManual/MITMManual.module.scss
  app/renderer/src/main/src/pages/mitm/MITMManual/MITMManual.tsx
  app/renderer/src/main/src/pages/mitm/MITMManual/MITMManualType.d.ts
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMHijackedContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.module.scss
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMServerStartForm.module.scss
  app/renderer/src/main/src/pages/mitm/MITMServerStartForm/MITMServerStartForm.tsx
  app/renderer/src/main/src/utils/editors.tsx
  app/renderer/src/main/src/yakitGV.ts
Labels: ready

#2514 Song/feat/history analysis adjust
  app/protos/grpc.proto
  app/renderer/src/main/src/components/DataExport/DataExport.tsx
  app/renderer/src/main/src/components/HTTPFlowDetail.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.module.scss
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTableForm.tsx
  app/renderer/src/main/src/components/HTTPHistory.module.scss
  app/renderer/src/main/src/components/HTTPHistory.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResizeType.d.ts
  app/renderer/src/main/src/defaultConstants/hTTPHistoryAnalysis.ts
  app/renderer/src/main/src/enums/history.ts
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequence.tsx
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/FuzzerSequenceType.d.ts
  app/renderer/src/main/src/pages/fuzzer/FuzzerSequence/ResponseAllDataCard.tsx
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerPage.tsx
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistory/HTTPHistoryFilter.module.scss
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistory/HTTPHistoryFilter.tsx
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistoryAnalysis.module.scss
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistoryAnalysis.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContentType.d.ts
  app/renderer/src/main/src/pages/mitm/MITMRule/MITMRule.tsx
  app/renderer/src/main/src/pages/mitm/MITMRule/MITMRuleType.ts
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMHijackedContent.tsx
  app/renderer/src/main/src/pages/yakitStore/viewers/base.tsx
  app/renderer/src/main/src/routes/newRoute.tsx
  app/renderer/src/main/src/store/pageInfo.ts
  app/renderer/src/main/src/yakitGV.ts
Labels: ready

#2516 Render Version To v1.04.18
  app/renderer/src/main/package.json
Labels: ready

#2517 v1.4.1-0418
  package.json
Labels: ready

#2519 Luoluo/fix/process-query
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMHijackedContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMLog.tsx
Labels: ready

#2521 Luoluo/feature/batch-manual
  app/renderer/src/main/prettier.config.js
  app/renderer/src/main/src/pages/mitm/MITMHacker/utils.ts
  app/renderer/src/main/src/pages/mitm/MITMManual/MITMManual.tsx
  app/renderer/src/main/src/pages/mitm/MITMManual/MITMManualType.d.ts
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMHijackedContent.tsx
  app/renderer/src/main/src/pages/mitm/MITMServerHijacking/MITMServerHijacking.module.scss
Labels: ready

#2526 Song/feat/tab batch add group
  app/renderer/src/main/src/pages/layout/mainOperatorContent/BatchAddNewGroup.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContent.tsx
  app/renderer/src/main/src/pages/layout/mainOperatorContent/MainOperatorContentType.d.ts
Labels: ready

#2524 Song/pref/history analysis
  app/protos/grpc.proto
  app/renderer/src/main/src/components/HTTPFlowTable/HTTPFlowTable.tsx
  app/renderer/src/main/src/components/TableVirtualResize/TableVirtualResize.tsx
  app/renderer/src/main/src/components/yakitUI/YakitDatePicker/YakitDatePicker.module.scss
  app/renderer/src/main/src/enums/history.ts
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistory/HTTPHistoryFilter.tsx
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistoryAnalysis.module.scss
  app/renderer/src/main/src/pages/hTTPHistoryAnalysis/HTTPHistoryAnalysis.tsx
  app/renderer/src/main/src/pages/mitm/MITMPage.tsx
  app/renderer/src/main/src/pages/mitm/MITMRule/MITMRule.tsx
  app/renderer/src/main/src/pages/plugins/operator/horizontalScrollCard/HorizontalScrollCard.module.scss
  app/renderer/src/main/src/pages/plugins/operator/horizontalScrollCard/HorizontalScrollCard.tsx
  app/renderer/src/main/src/pages/plugins/operator/horizontalScrollCard/HorizontalScrollCardType.d.ts
  app/renderer/src/main/src/utils/eventBus/events/history.ts
Labels: ready

#2523 feat: webfuzzer热加载代码模板点击加气泡确认框
  app/renderer/src/main/src/pages/fuzzer/HTTPFuzzerHotPatch.tsx
Labels: ready

#2531 v1.4.1-0425
  package.json
Labels: Merge after publishing

#2535 Render Version To v1.04.26/render
  app/renderer/src/main/package.json
Labels: Merge after publishing

#2534 feat：企业版上传插件库
  app/main/api/upload.js
  app/renderer/src/main/src/components/layout/UILayout.tsx
  app/renderer/src/main/src/hook/useUploadOSS/useUploadOSS.ts
  app/renderer/src/main/src/pages/plugins/manage/PluginManage.tsx
Labels: ready
